CASMINST-5347: Add retries and additional output to some upgrade workflows; Remove unused script; Write stage names to log file in prerequisites.sh

diff --git a/workflows/ncn/worker/worker.drain.yaml b/workflows/ncn/worker/worker.drain.yaml
--- a/workflows/ncn/worker/worker.drain.yaml
+++ b/workflows/ncn/worker/worker.drain.yaml
@@ -33,64 +33,50 @@ tasks:
           value: "{{ `{{inputs.parameters.dryRun}}` }}"
         - name: scriptContent
           value: |
-            TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
-            TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
-                jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
-
+            set -x
             set -o pipefail
+            {{- include "common.helper-functions" . | indent 12 }}
 
-            # Retry CFS command if needed
-            COUNT=0
-            while true; do
-                ENABLED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components/${TARGET_XNAME}" | jq -r '.enabled') && break
-                let COUNT+=1
-                if [[ ${COUNT} -gt 12 ]]; then
-                    echo "ERROR: Even after retries, command pipeline failed querying CFS component '${TARGET_XNAME}'"
-                    exit 1
-                fi
-                echo "WARNING: Command pipeline failed querying CFS component '${TARGET_XNAME}'. Retrying after 5 seconds."
-                sleep 5
-            done
+            # These function are defined in the above include statement. 
+            set_target_xname
+            
+            # set_cfs_status_file will retry the API request multiple times if needed.
+            # The result will be stored in the $CFS_STATUS_FILE file
+            set_cfs_status_file
+
+            ENABLED=$(cat "${CFS_STATUS_FILE}" | jq -r '.enabled')
+            dtecho "ENABLED=$ENABLED"
             if [[ ${ENABLED} == false ]]; then
-              exit 0
+                exit 0
             elif [[ ${ENABLED} != true ]]; then
-              echo "ERROR: Unexpected contents of 'enabled' field for CFS component '${TARGET_XNAME}': '${ENABLED}'"
-              exit 1
+                dtecho "ERROR: Unexpected contents of 'enabled' field for CFS component '${TARGET_XNAME}': '${ENABLED}'"
+                exit 1
             fi
-            echo "CFS component '${TARGET_XNAME}' is enabled"
+            dtecho "CFS component '${TARGET_XNAME}' is enabled"
 
-            # Retry CFS command if needed
-            COUNT=0
-            while true; do
-                DESIRED_CONFIG=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components/${TARGET_XNAME}" | jq -r '.desiredConfig') && break
-                let COUNT+=1
-                if [[ ${COUNT} -gt 12 ]]; then
-                    echo "ERROR: Even after retries, command pipeline failed querying CFS component '${TARGET_XNAME}'"
-                    exit 1
-                fi
-                echo "WARNING: Command pipeline failed querying CFS component '${TARGET_XNAME}'. Retrying after 5 seconds."
-                sleep 5
-            done
+            DESIRED_CONFIG=$(cat "${CFS_STATUS_FILE}" | jq -r '.desiredConfig')
             if [[ -z ${DESIRED_CONFIG} ]]; then
-              exit 0
+                dtecho "CFS component '${TARGET_XNAME}' has no desired configuration"
+                exit 0
             fi
-            echo "Desired configuration for CFS component '${TARGET_XNAME}' is '${DESIRED_CONFIG}'"
+            dtecho "Desired configuration for CFS component '${TARGET_XNAME}' is '${DESIRED_CONFIG}'"
 
-            while true; do
-              RESULT=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=pending" | jq length)
-              if [[ "$RESULT" -eq 0 ]]; then
-                break
-              fi
-              echo "Waiting for configuration to complete.  ${RESULT} components remaining."
-              sleep 30
+            CONFIG_STATUS=$(cat "${CFS_STATUS_FILE}" | jq -r '.configurationStatus')
+            dtecho "CONFIG_STATUS=$CONFIG_STATUS"
+            while [[ $CONFIG_STATUS == pending ]]; do
+                dtecho "Waiting for CFS configuration to complete on ${TARGET_XNAME}"
+                sleep 30
+                set_cfs_status_file
+                CONFIG_STATUS=$(cat "${CFS_STATUS_FILE}" | jq -r '.configurationStatus')
+                dtecho "CFS configuration status of $(target_xname_and_name) is $CONFIG_STATUS"
             done
 
-            CONFIGURED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=configured" | jq length)
-            FAILED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=failed" | jq length)
-            echo "Configuration complete. $CONFIGURED component(s) completed successfully.  $FAILED component(s) failed."
-            if [ "$FAILED" -ne "0" ]; then
-              echo "The following components failed: $(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=failed"  | jq -r '. | map(.id) | join(",")')"
-              exit 1
+            if [[ $CONFIG_STATUS == failed ]]; then
+                dtecho "$(target_xname_and_name) failed to successfully complete its CFS configuration"
+                exit 1
+            elif [[ $CONFIG_STATUS != configured ]]; then
+                dtecho "$(target_xname_and_name) has unexpected CFS status: $CONFIG_STATUS"
+                exit 1
             fi
   - name: clear-cfs-state
     dependencies:
@@ -104,13 +90,44 @@ tasks:
           value: "{{ `{{inputs.parameters.dryRun}}` }}"
         - name: scriptContent
           value: |
-            TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
-            TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
-                jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
+            set -x
+            {{- include "common.helper-functions" . | indent 12 }}
 
+            # These function are defined in the above include statement. 
+            set_api_token
+            set_target_xname
+
+            set_cfs_status_file
+            ENABLED=$(cat "${CFS_STATUS_FILE}" | jq -r '.enabled')
+            dtecho "ENABLED=$ENABLED"
+            if [[ ${ENABLED} == false ]]; then
+                # If it is already disabled, then we don't need to disable it
+                exit 0
+            elif [[ ${ENABLED} != true ]]; then
+                dtecho "ERROR: Unexpected contents of 'enabled' field for CFS component '${TARGET_XNAME}': '${ENABLED}'"
+                exit 1
+            fi
+            dtecho "CFS component '${TARGET_XNAME}' is enabled"
+
+            # Disable component in CFS
             curl -s -k -H "Authorization: Bearer ${TOKEN}" -X PATCH "https://api-gw-service-nmn.local/apis/cfs/v2/components/${TARGET_XNAME}" \
               -H 'Content-Type: application/json' \
-              -d '{"enabled": false, "state": []}'
+              -d '{"enabled": false}'
+
+            # Verify that it was disabled
+            set_cfs_status_file
+            ENABLED=$(cat "${CFS_STATUS_FILE}" | jq -r '.enabled')
+            dtecho "ENABLED=$ENABLED"
+            if [[ ${ENABLED} == false ]]; then
+                # If it is already disabled, then we don't need to disable it
+                exit 0
+            elif [[ ${ENABLED} != true ]]; then
+                dtecho "ERROR: Unexpected contents of 'enabled' field for CFS component '${TARGET_XNAME}': '${ENABLED}'"
+                exit 1
+            else
+                dtecho "ERROR: CFS component '${TARGET_XNAME}' is still enabled, even after attempting to disable it"
+                exit 1
+            fi
   - name: ensure-etcd-pods-are-healthy
     templateRef:
       name: ssh-template
@@ -149,7 +166,7 @@ tasks:
                     echo "ERROR - Etcd cluster: $cluster should have 3 pods running but only $numOfPods are running"
                     continue
                   else
-                    echo "Etcd cluster: $cluster have 3 pods running"
+                    echo "Etcd cluster: $cluster has 3 pods running"
                     break
                   fi
                 done
@@ -194,7 +211,7 @@ tasks:
                   echo "$label has met with the minimum requirement"
                   break;
                 fi
-                echo "$label hasn't met with the minimum requirement(2): $numOfRunningPods"
+                echo "$label hasn't met with the minimum requirement (2): $numOfRunningPods"
                 sleep 5
               done
             done
@@ -289,9 +306,18 @@ tasks:
           value: "{{ `{{inputs.parameters.dryRun}}` }}"
         - name: scriptContent
           value: |
-            TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
-            TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
-                jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
+            set -x
+            set -o pipefail
+            {{- include "common.helper-functions" . | indent 12 }}
+
+            set_target_xname
             /host_usr_bin/csi handoff bss-update-param --delete metal.no-wipe --limit $TARGET_XNAME
-            /host_usr_bin/csi handoff bss-update-param --set metal.no-wipe=0 --limit $TARGET_XNAME
+
+            TRIES=0
+            ACTION="set metal.no-wipe=0 in BSS for $TARGET_XNAME"
+            echo "Trying to: $ACTION"
+            while ! /host_usr_bin/csi handoff bss-update-param --set metal.no-wipe=0 --limit $TARGET_XNAME ; do
+              sleep_or_exit
+            done
+            echo "Completed: $ACTION"
 {{end}}
diff --git a/workflows/ncn/worker/worker.rebuild.yaml b/workflows/ncn/worker/worker.rebuild.yaml
--- a/workflows/ncn/worker/worker.rebuild.yaml
+++ b/workflows/ncn/worker/worker.rebuild.yaml
@@ -70,7 +70,7 @@ spec:
   affinity:
     nodeAffinity:
       # avoid putting workflow jobs onto workers that will be rebuilt
-      # this label is set onto each workers at beginning of workflow
+      # this label is set onto each worker at beginning of workflow
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
@@ -116,6 +116,7 @@ spec:
                   value: "{{$.DryRun}}"  
                 - name: scriptContent
                   value: |
+                    set -x
                     targetNcns="{{.TargetNcns}}"
                     # remove '[' and ']'
                     targetNcns=${targetNcns:1:-1}
@@ -134,26 +135,47 @@ spec:
                       fi
                     done
 
+                    echo "nodeMoveTo=${nodeMoveTo}"                    
                     echo
 
                     pods=( "nexus" "ipxe" "kea" "cray-cfs-api-db" )
-                    for pod in ${pods[@]};do
-                      podName=$(kubectl get pods --all-namespaces | awk '{print $2}' | grep $pod)
-                      if [[ -z $podName ]];then
-                        echo "Couldn't not find pod: $pod"
-                        echo "something is wrong"
-                        exit 1
-                      fi                 
-                      
-                      currentNode=$(kubectl get po -A -o wide | grep $podName | awk '{print $8}')
-                      if [[ "$nodeMoveTo" != "$currentNode" ]]; then
-                        echo "Move Pod: $podName to Node: $nodeMoveTo"
-                        /opt/cray/platform-utils/move_pod.sh $podName $nodeMoveTo > /dev/null
-                      fi
+                    for pod in ${pods[@]};do                        
+                        currentNode=""
+                        podName=$(kubectl get pods --all-namespaces | awk '{print $2}' | grep $pod)
+                        if [[ -z $podName ]];then
+                            echo "Something is wrong. Could not find pod: $pod"
+                            exit 1
+                        fi
+                        echo "pod=$pod podName=$podName"                        
+                        while [[ $currentNode != $nodeMoveTo ]]; do                    
+                            currentNode=$(kubectl get po -A -o wide | grep $podName | awk '{print $8}')
+                            if [[ -z $currentNode ]]; then
+                                echo "Unable to determine current node for pod $podName"
+                                exit 1
+                            fi
 
-                      podName=$(kubectl get pods --all-namespaces | awk '{print $2}' | grep $pod)
-                      ns=$(kubectl get po -A | grep $podName | awk '{print $1}')
-                      kubectl wait --for=condition=ready pod $podName -n $ns --timeout=5m
+                            echo "pod=$pod podName=$podName currentNode=$currentNode"
+                            if [[ "$nodeMoveTo" != "$currentNode" ]]; then
+                                echo "Move Pod: $podName to Node: $nodeMoveTo"
+                                /opt/cray/platform-utils/move_pod.sh $podName $nodeMoveTo
+                            fi
+
+                            podName=$(kubectl get pods --all-namespaces | awk '{print $2}' | grep $pod)
+                            if [[ -z $podName ]];then
+                                echo "Something is wrong. Could not find pod: $pod"
+                                exit 1
+                            fi
+                            ns=$(kubectl get po -A | grep $podName | awk '{print $1}')
+                            if [[ -z $ns ]];then
+                                echo "Something is wrong. Could not find namespace for pod: $podName"
+                                exit 1
+                            fi
+                            kubectl wait --for=condition=ready pod $podName -n $ns --timeout=5m
+
+                            # Verify that pod is now on the expected node
+                            currentNode=$(kubectl get po -A -o wide | grep $podName | awk '{print $8}')
+                            echo "pod=$pod podName=$podName currentNode=$currentNode"
+                        done
                     done
           {{- range $index,$value := .TargetNcns }}
           - name: add-labels-{{$value}}
@@ -184,7 +206,7 @@ spec:
           # wipe and reboot: parallel
           #     once a worker node is drained from k8s
           #     we can safely wipe and reboot this node
-          #     regardless of what state other nodes are
+          #     regardless of what state other nodes are in
           - name: wipe-and-reboot-{{$value}}
             dependencies: 
               - drain-{{$value}}
