Revert "CASMTRIAGE-4256 remove cfs before upgrade" (#2566)
Revert "CASMTRIAGE-4256 remove cfs before upgrade (#2553)"

This reverts commit 5e9a78a868215e45854f8cd8c051321441b31f86.

(cherry picked from commit 9fc304bc43fed6c3182ede54f9a1b8389a7e75a3)

Co-authored-by: Dennis Walker <denniswalker@me.com>

diff --git a/workflows/ncn/worker/worker.drain.yaml b/workflows/ncn/worker/worker.drain.yaml
--- a/workflows/ncn/worker/worker.drain.yaml
+++ b/workflows/ncn/worker/worker.drain.yaml
@@ -23,6 +23,94 @@
 #
 {{define "worker.drain"}}
 tasks:
+  - name: wait-for-cfs
+    templateRef:
+      name: kubectl-and-curl-template
+      template: shell-script
+    arguments:
+      parameters:
+        - name: dryRun
+          value: "{{ `{{inputs.parameters.dryRun}}` }}"
+        - name: scriptContent
+          value: |
+            TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
+            TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
+                jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
+
+            set -o pipefail
+
+            # Retry CFS command if needed
+            COUNT=0
+            while true; do
+                ENABLED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components/${TARGET_XNAME}" | jq -r '.enabled') && break
+                let COUNT+=1
+                if [[ ${COUNT} -gt 12 ]]; then
+                    echo "ERROR: Even after retries, command pipeline failed querying CFS component '${TARGET_XNAME}'"
+                    exit 1
+                fi
+                echo "WARNING: Command pipeline failed querying CFS component '${TARGET_XNAME}'. Retrying after 5 seconds."
+                sleep 5
+            done
+            if [[ ${ENABLED} == false ]]; then
+              exit 0
+            elif [[ ${ENABLED} != true ]]; then
+              echo "ERROR: Unexpected contents of 'enabled' field for CFS component '${TARGET_XNAME}': '${ENABLED}'"
+              exit 1
+            fi
+            echo "CFS component '${TARGET_XNAME}' is enabled"
+
+            # Retry CFS command if needed
+            COUNT=0
+            while true; do
+                DESIRED_CONFIG=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components/${TARGET_XNAME}" | jq -r '.desiredConfig') && break
+                let COUNT+=1
+                if [[ ${COUNT} -gt 12 ]]; then
+                    echo "ERROR: Even after retries, command pipeline failed querying CFS component '${TARGET_XNAME}'"
+                    exit 1
+                fi
+                echo "WARNING: Command pipeline failed querying CFS component '${TARGET_XNAME}'. Retrying after 5 seconds."
+                sleep 5
+            done
+            if [[ -z ${DESIRED_CONFIG} ]]; then
+              exit 0
+            fi
+            echo "Desired configuration for CFS component '${TARGET_XNAME}' is '${DESIRED_CONFIG}'"
+
+            while true; do
+              RESULT=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=pending" | jq length)
+              if [[ "$RESULT" -eq 0 ]]; then
+                break
+              fi
+              echo "Waiting for configuration to complete.  ${RESULT} components remaining."
+              sleep 30
+            done
+
+            CONFIGURED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=configured" | jq length)
+            FAILED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=failed" | jq length)
+            echo "Configuration complete. $CONFIGURED component(s) completed successfully.  $FAILED component(s) failed."
+            if [ "$FAILED" -ne "0" ]; then
+              echo "The following components failed: $(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=failed"  | jq -r '. | map(.id) | join(",")')"
+              exit 1
+            fi
+  - name: clear-cfs-state
+    dependencies:
+      - wait-for-cfs
+    templateRef:
+      name: kubectl-and-curl-template
+      template: shell-script
+    arguments:
+      parameters:
+        - name: dryRun
+          value: "{{ `{{inputs.parameters.dryRun}}` }}"
+        - name: scriptContent
+          value: |
+            TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
+            TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
+                jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
+
+            curl -s -k -H "Authorization: Bearer ${TOKEN}" -X PATCH "https://api-gw-service-nmn.local/apis/cfs/v2/components/${TARGET_XNAME}" \
+              -H 'Content-Type: application/json' \
+              -d '{"enabled": false, "state": []}'
   - name: ensure-etcd-pods-are-healthy
     templateRef:
       name: ssh-template
@@ -143,6 +231,7 @@ tasks:
             fi
   - name: drain
     dependencies:
+      - clear-cfs-state
       - ensure-etcd-pods-are-healthy
       - ensure-pg-pods-are-healthy
       - ensure-critical-pods-are-running
@@ -186,6 +275,7 @@ tasks:
             done
   - name: update-bss
     dependencies:
+      - clear-cfs-state
       - ensure-etcd-pods-are-healthy
       - ensure-pg-pods-are-healthy
       - ensure-critical-pods-are-running
