Needs reviews and testing

diff --git a/workflows/ncn/worker/worker.post-rebuild.yaml b/workflows/ncn/worker/worker.post-rebuild.yaml
--- a/workflows/ncn/worker/worker.post-rebuild.yaml
+++ b/workflows/ncn/worker/worker.post-rebuild.yaml
@@ -33,9 +33,19 @@ tasks:
           value: "{{ `{{inputs.parameters.dryRun}}` }}"
         - name: scriptContent
           value: |
+            {{- include "lib.sh" | indent 12 }}
+
+            trap libcleanup EXIT
+
+            tmpfile=$(libtmpfile update-bss-no-wipe)
+
             TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
-            TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
-                jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
+
+            # REVIEW: Fatal if curl fails here?
+            curl --output "${tmpfile}" --header "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management"
+
+            # REVIEW: Fatal if jq fails?
+            TARGET_XNAME=$(jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname" "${tmpfile}")
             /host_usr_bin/csi handoff bss-update-param --set metal.no-wipe=1 --limit $TARGET_XNAME
   - name: wait-for-cfs-after-rebuild
     templateRef:
@@ -47,10 +57,21 @@ tasks:
           value: "{{ `{{inputs.parameters.dryRun}}` }}"
         - name: scriptContent
           value: |
-            TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
-            TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
-                jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
+            {{- include "lib.sh" | indent 12 }}
 
+            trap libcleanup EXIT
+
+            tmpfile=$(libtmpfile update-bss-no-wipe)
+
+            TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
+
+            # REVIEW: Default fatal
+            curl --output "${tmpfile}" --header "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management"
+
+            # REVIEW: Default fatal
+            TARGET_XNAME=$(jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname" "${tmpfile}")
+
+            # REVIEW: No longer needed, and likely shouldn't be used
             set -o pipefail
 
             # Wait for component to become enabled (this should happen whether or not there is a desired configuration)
@@ -58,7 +79,17 @@ tasks:
                 # Retry CFS command if needed
                 COUNT=0
                 while true; do
-                    ENABLED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components/${TARGET_XNAME}" | jq -r '.enabled') && break
+                    # REVIEW: In a retry loop so we'll use the non exit() version of hooks
+                    #shellcheck disable=SC2034
+                    CURLFN=curlretry
+
+                    curl --output "${tmpfile}" --header "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components/${TARGET_XNAME}"
+
+                    # REVIEW: In a retry loop so we'll use the non exit() version of hooks
+                    #shellcheck disable=SC2034
+                    JQTESTFAILFN=jqretry
+
+                    ENABLED=$(jq -r '.enabled' "${tmpfile}") && break
                     let COUNT+=1
                     if [[ ${COUNT} -gt 12 ]]; then
                         echo "ERROR: Even after retries, command pipeline failed querying CFS component '${TARGET_XNAME}'"
@@ -82,7 +113,17 @@ tasks:
             # Retry CFS command if needed
             COUNT=0
             while true; do
-                DESIRED_CONFIG=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components/${TARGET_XNAME}" | jq -r '.desiredConfig') && break
+                # REVIEW: In a retry loop so we'll use the non exit() version of hooks
+                #shellcheck disable=SC2034
+                CURLFN=curlretry
+
+                curl --output "${tmpfile}" "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components/${TARGET_XNAME}"
+
+                # REVIEW: In a retry loop so we'll use the non exit() version of hooks
+                #shellcheck disable=SC2034
+                JQTESTFAILFN=jqretry
+
+                DESIRED_CONFIG=$(jq -r '.desiredConfig' "${tmpfile}") && break
                 let COUNT+=1
                 if [[ ${COUNT} -gt 12 ]]; then
                     echo "ERROR: Even after retries, command pipeline failed querying CFS component '${TARGET_XNAME}'"
@@ -97,7 +138,16 @@ tasks:
             echo "Desired configuration for CFS component '${TARGET_XNAME}' is '${DESIRED_CONFIG}'"
 
             while true; do
-              RESULT=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=pending" | jq length)
+              # REVIEW: In a retry loop so we'll use the non exit() version of hooks
+              #shellcheck disable=SC2034
+              CURLFN=curlretry
+              curl --output "${tmpfile}" --header "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=pending")
+
+              # REVIEW: In a retry loop so we'll use the non exit() version of hooks
+              #shellcheck disable=SC2034
+              JQTESTFAILFN=jqretry
+
+              RESULT=$(jq length "${tmpfile}")
               if [[ "$RESULT" -eq 0 ]]; then
                 break
               fi
@@ -105,10 +155,26 @@ tasks:
               sleep 30
             done
 
-            CONFIGURED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=configured" | jq length)
-            FAILED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=failed" | jq length)
+            # Set hooks back to the exit versions.
+            CURLFN=curlfatal
+            JQTESTFAILFN=jqfatal
+
+            # REVIEW: Default fatal
+            curl --output "${tmpfile}" --header "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=configured"
+
+            # REVIEW: Default fatal
+            CONFIGURED=$(jq length "${tmpfile}")
+
+            # REVIEW: Default fatal
+            curl --output "${tmpfile}" --header  "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=failed"
+
+            # REVIEW: Default fatal
+            FAILED=$(jq length "${tmpfile}")
             echo "Configuration complete. $CONFIGURED component(s) completed successfully.  $FAILED component(s) failed."
             if [ "$FAILED" -ne "0" ]; then
+              # REVIEW: This should just reuse the tmpfile I think, we can save
+              # a call here, but if so even if jq fails it looks like we fail
+              # that before the implicit exit
               echo "The following components failed: $(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=failed"  | jq -r '. | map(.id) | join(",")')"
               exit 1
             fi
diff --git a/workflows/ncn/worker/worker.wipe-and-reboot.yaml b/workflows/ncn/worker/worker.wipe-and-reboot.yaml
--- a/workflows/ncn/worker/worker.wipe-and-reboot.yaml
+++ b/workflows/ncn/worker/worker.wipe-and-reboot.yaml
@@ -35,7 +35,15 @@ tasks:
           value: |
             {{- include "common.envar" . | indent 12 }}
 
-            if ! cray bss bootparameters list --hosts $TARGET_XNAME --format json | jq '.[] |."cloud-init"."user-data".ntp' | grep -q '/etc/chrony.d/cray.conf'; then
+            trap libcleanup EXIT
+
+            tmpfile=$(libtmpfile validate-bss-ntp)
+
+            # REVIEW: Default fatal
+            cray bss bootparameters list --hosts $TARGET_XNAME --format json > "${tmpfile}"
+
+            # REVIEW: Default fatal
+            if ! jq '.[] |."cloud-init"."user-data".ntp' | grep -q '/etc/chrony.d/cray.conf'; then
               echo "${TARGET_NCN} is missing NTP data in BSS. Please see the procedure which can be found in the 'Known Issues and Bugs' section titled 'Fix BSS Metadata' on the 'Configure NTP on NCNs' page of the CSM documentation."
               exit 1
             fi
@@ -51,16 +59,29 @@ tasks:
           value: "{{ `{{inputs.parameters.dryRun}}` }}"
         - name: scriptContent
           value: |
+            {{- include "lib.sh" | indent 12 }}
+
+            trap libcleanup EXIT
+
             TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
-            TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
-                jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
+            tmpfile=$(libtmpfile get-bootscript-last-access-timestamp)
+
+            # REVIEW: Default fatal
+            curl --output "${tmpfile}" --header "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management"
+
+            # REVIEW: Default fatal
+            TARGET_XNAME=$(jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname" "${tmpfile}")
             /host_usr_bin/csi handoff bss-update-param --set metal.no-wipe=0 --limit $TARGET_XNAME
 
-            bootscript_last_epoch=$(curl -s -k -H "Content-Type: application/json" \
-            -H "Authorization: Bearer ${TOKEN}" \
-            "https://api-gw-service-nmn.local/apis/bss/boot/v1/endpoint-history?name=$TARGET_XNAME" \
-            | jq '.[]| select(.endpoint=="bootscript")|.last_epoch' 2> /dev/null)
-            
+            tmpfile=$(libtmpfile "basename $0")
+
+            # REVIEW: Default fatal
+            curl --output "${tmpfile}" --header "Content-Type: application/json" \
+              --header "Authorization: Bearer ${TOKEN}" \
+              "https://api-gw-service-nmn.local/apis/bss/boot/v1/endpoint-history?name=$TARGET_XNAME"
+            # REVIEW: Default fatal
+            bootscript_last_epoch=$(jq '.[]| select(.endpoint=="bootscript")|.last_epoch' "${tmpfile}" 2> /dev/null )
+
             if [[ $bootscript_last_epoch -gt 0 ]]; then
               echo $bootscript_last_epoch
             else
@@ -81,7 +102,9 @@ tasks:
         - name: scriptContent
           value: |
             {{- include "common.envar" . | indent 12 }}
-            
+
+            trap libcleanup EXIT
+
             cat <<'EOF' > set-next-boot-to-pxe.sh
               efibootmgr # print before
               efibootmgr | grep -P '(UEFI OS|cray)' | awk -F'[^0-9]*' '{print $0}' | sed 's/^Boot//g' | awk '{print $1}' | tr -d '*' | xargs -r -i efibootmgr -b {} -B
@@ -91,7 +114,7 @@ tasks:
               mount -L BOOTRAID -T /etc/fstab.metal
               rm -rf /metal/recovery/*
             EOF
-            
+
             chmod +x set-next-boot-to-pxe.sh
             scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null set-next-boot-to-pxe.sh $TARGET_NCN:/tmp/set-next-boot-to-pxe.sh
             ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $TARGET_NCN '/tmp/set-next-boot-to-pxe.sh'
@@ -109,10 +132,12 @@ tasks:
         - name: scriptContent
           value: |
             {{- include "common.envar" . | indent 12 }}
-            
+
+            trap libcleanup EXIT
+
             # Set ncn to pxe boot
             ipmitool -I lanplus -U ${IPMI_USERNAME} -E -H $TARGET_NCN_mgmt_host chassis bootdev pxe options=efiboot
-            
+
             powerStatus=$(ipmitool -I lanplus -U ${IPMI_USERNAME} -E -H $TARGET_NCN_mgmt_host chassis power status)
             if [[ "$powerStatus" == *"is on"* ]]; then
               # power cycle node
@@ -134,8 +159,10 @@ tasks:
           value: |
             {{- include "common.envar" . | indent 12 }}
 
+            trap libcleanup EXIT
+
             bootscript_last_epoch="{{ `{{tasks.get-bootscript-last-access-timestamp.outputs.result}}` }}"
-            
+
             # wait for boot
             counter=0
             echo "waiting for boot: $TARGET_NCN ..."
@@ -144,10 +171,18 @@ tasks:
                 set +e
                 while true
                 do
-                    tmp_bootscript_last_epoch=$(curl -s -k -H "Content-Type: application/json" \
-                        -H "Authorization: Bearer ${TOKEN}" \
-                        "https://api-gw-service-nmn.local/apis/bss/boot/v1/endpoint-history?name=$TARGET_XNAME" \
-                        | jq '.[]| select(.endpoint=="bootscript")|.last_epoch' 2> /dev/null)
+                    tmpfile=$(libtmpfile wait-for-boot)
+                    # REVIEW: In a retry loop so we'll use the non exit() version of hooks
+                    #shellcheck disable=SC2034
+                    CURLFN=curlretry
+                    curl --output="${tmpfile}" --header "Content-Type: application/json" \
+                        --header "Authorization: Bearer ${TOKEN}" \
+                        "https://api-gw-service-nmn.local/apis/bss/boot/v1/endpoint-history?name=$TARGET_XNAME"
+
+                    # REVIEW: In a retry loop so we'll use the non exit() version of hooks
+                    #shellcheck disable=SC2034
+                    JQTESTFAILFN=jqretry
+                    tmp_bootscript_last_epoch=$(jq '.[]| select(.endpoint=="bootscript")|.last_epoch' "${tmpfile}" 2> /dev/null)
                     if [[ $? -eq 0 ]]; then
                         break
                     fi
@@ -181,6 +216,8 @@ tasks:
           value: |
             {{- include "common.envar" . | indent 12 }}
 
+            trap libcleanup EXIT
+
             # wait random seconds (1-10s) until ssh is working
             echo "wait for ssh ..."
             while ! ssh "${TARGET_NCN}" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 'ls /var/log/cloud-init-output.log'
@@ -198,6 +235,7 @@ tasks:
                 echo "waiting for cloud-init: $TARGET_NCN ..."
                 sleep 20
             done
+            # REVIEW: this is the end of the script no? Not needed
             # Restore set -e
             set -e
   - name: "wait-for-k8s"
@@ -241,6 +279,8 @@ tasks:
         - name: scriptContent
           value: |
             {{- include "common.envar" . | indent 12 }}
+
+            trap libcleanup EXIT
 
             ssh ${TARGET_NCN} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 'cray init --no-auth --overwrite --hostname https://api-gw-service-nmn.local'
 {{end}}
