CASMINST-5347: Add retries and additional output to some upgrade workflows; Remove unused script; Write stage names to log file in prerequisites.sh
(cherry picked from commit 76e1d941cfc8e3ddb66d1a668f6806fafc757ee4)

diff --git a/workflows/ncn/worker/worker.post-rebuild.yaml b/workflows/ncn/worker/worker.post-rebuild.yaml
--- a/workflows/ncn/worker/worker.post-rebuild.yaml
+++ b/workflows/ncn/worker/worker.post-rebuild.yaml
@@ -33,10 +33,21 @@ tasks:
           value: "{{ `{{inputs.parameters.dryRun}}` }}"
         - name: scriptContent
           value: |
-            TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
-            TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
-                jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
-            /host_usr_bin/csi handoff bss-update-param --set metal.no-wipe=1 --limit $TARGET_XNAME
+            set -x
+            set -o pipefail
+            {{- include "common.helper-functions" . | indent 12 }}
+
+            set_api_token
+            set_target_xname
+
+            TRIES=0
+            ACTION="set metal.no-wipe=1 in BSS for $TARGET_XNAME"
+            echo "Trying to: $ACTION"
+            while ! /host_usr_bin/csi handoff bss-update-param --set metal.no-wipe=1 --limit $TARGET_XNAME ; do
+              # sleep_or_exit is imported via common.retry
+              sleep_or_exit
+            done
+            echo "Completed: $ACTION"
   - name: wait-for-cfs-after-rebuild
     templateRef:
       name: kubectl-and-curl-template
@@ -47,70 +58,57 @@ tasks:
           value: "{{ `{{inputs.parameters.dryRun}}` }}"
         - name: scriptContent
           value: |
-            TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
-            TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
-                jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
-
+            set -x
             set -o pipefail
+            {{- include "common.helper-functions" . | indent 12 }}
+
+            # These function are defined in the above include statement. 
+            set_target_xname
+            
+            # set_cfs_status_file will retry the API request multiple times if needed.
+            # The result will be stored in the $CFS_STATUS_FILE file
+            set_cfs_status_file
 
             # Wait for component to become enabled (this should happen whether or not there is a desired configuration)
-            while true; do
-                # Retry CFS command if needed
-                COUNT=0
-                while true; do
-                    ENABLED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components/${TARGET_XNAME}" | jq -r '.enabled') && break
-                    let COUNT+=1
-                    if [[ ${COUNT} -gt 12 ]]; then
-                        echo "ERROR: Even after retries, command pipeline failed querying CFS component '${TARGET_XNAME}'"
-                        exit 1
-                    fi
-                    echo "WARNING: Command pipeline failed querying CFS component '${TARGET_XNAME}'. Retrying after 5 seconds."
-                    sleep 5
-                done
-                if [[ ${ENABLED} == false ]]; then
-                    echo "CFS component '${TARGET_XNAME}' still not enabled. Checking again after 30 seconds."
-                    sleep 30
-                    continue
-                elif [[ ${ENABLED} != true ]]; then
-                    echo "ERROR: Unexpected contents of 'enabled' field for CFS component '${TARGET_XNAME}': '${ENABLED}'"
+            ENABLED=$(cat "${CFS_STATUS_FILE}" | jq -r '.enabled')
+            dtecho "ENABLED=$ENABLED"
+            while [[ $ENABLED != true ]]; then
+                if [[ $ENABLED != false ]]; then
+                    dtecho "ERROR: Unexpected contents of 'enabled' field for CFS component '${TARGET_XNAME}': '${ENABLED}'"
                     exit 1
                 fi
-                echo "CFS component '${TARGET_XNAME}' is enabled"
-                break
-            done
 
-            # Retry CFS command if needed
-            COUNT=0
-            while true; do
-                DESIRED_CONFIG=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components/${TARGET_XNAME}" | jq -r '.desiredConfig') && break
-                let COUNT+=1
-                if [[ ${COUNT} -gt 12 ]]; then
-                    echo "ERROR: Even after retries, command pipeline failed querying CFS component '${TARGET_XNAME}'"
-                    exit 1
-                fi
-                echo "WARNING: Command pipeline failed querying CFS component '${TARGET_XNAME}'. Retrying after 5 seconds."
-                sleep 5
+                echo "CFS component '${TARGET_XNAME}' still not enabled. Checking again after 30 seconds."
+                sleep 30
+                set_cfs_status_file
+                ENABLED=$(cat "${CFS_STATUS_FILE}" | jq -r '.enabled')
+                dtecho "ENABLED=$ENABLED"
             done
+            echo "CFS component '${TARGET_XNAME}' is enabled"
+
+            DESIRED_CONFIG=$(cat "${CFS_STATUS_FILE}" | jq -r '.desiredConfig')
             if [[ -z ${DESIRED_CONFIG} ]]; then
-              exit 0
+                dtecho "CFS component '${TARGET_XNAME}' has no desired configuration"
+                exit 0
             fi
-            echo "Desired configuration for CFS component '${TARGET_XNAME}' is '${DESIRED_CONFIG}'"
+            dtecho "Desired configuration for CFS component '${TARGET_XNAME}' is '${DESIRED_CONFIG}'"
 
-            while true; do
-              RESULT=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=pending" | jq length)
-              if [[ "$RESULT" -eq 0 ]]; then
-                break
-              fi
-              echo "Waiting for configuration to complete.  ${RESULT} components remaining."
-              sleep 30
+            CONFIG_STATUS=$(cat "${CFS_STATUS_FILE}" | jq -r '.configurationStatus')
+            dtecho "CONFIG_STATUS=$CONFIG_STATUS"
+            while [[ $CONFIG_STATUS == pending ]]; do
+                dtecho "Waiting for CFS configuration to complete on ${TARGET_XNAME}"
+                sleep 30
+                set_cfs_status_file
+                CONFIG_STATUS=$(cat "${CFS_STATUS_FILE}" | jq -r '.configurationStatus')
+                dtecho "CFS configuration status of $(target_xname_and_name) is $CONFIG_STATUS"
             done
 
-            CONFIGURED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=configured" | jq length)
-            FAILED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=failed" | jq length)
-            echo "Configuration complete. $CONFIGURED component(s) completed successfully.  $FAILED component(s) failed."
-            if [ "$FAILED" -ne "0" ]; then
-              echo "The following components failed: $(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=failed"  | jq -r '. | map(.id) | join(",")')"
-              exit 1
+            if [[ $CONFIG_STATUS == failed ]]; then
+                dtecho "$(target_xname_and_name) failed to successfully complete its CFS configuration"
+                exit 1
+            elif [[ $CONFIG_STATUS != configured ]]; then
+                dtecho "$(target_xname_and_name) has unexpected CFS status: $CONFIG_STATUS"
+                exit 1
             fi
   - name: ensure-csm-rpms-installed
     templateRef:
