Update workflows/ncn/worker/worker.post-rebuild.yaml
Co-authored-by: Mitch Harding <mitchell.harding@hpe.com>
Signed-off-by: Di Zou <83423760+dzou-hpe@users.noreply.github.com>

diff --git a/workflows/ncn/worker/worker.post-rebuild.yaml b/workflows/ncn/worker/worker.post-rebuild.yaml
--- a/workflows/ncn/worker/worker.post-rebuild.yaml
+++ b/workflows/ncn/worker/worker.post-rebuild.yaml
@@ -51,10 +51,50 @@ tasks:
             TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
                 jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
 
-            DESIRED_CONFIG_EMPTY=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/component/${TARGET_XNAME}" | jq -r '.desiredConfig' | grep '^$' | wc -l )
-            if [[ ${DESIRED_CONFIG_EMPTY} -eq 1 ]]; then
+            set -o pipefail
+
+            # Wait for component to become enabled (this should happen whether or not there is a desired configuration)
+            while true; do
+                # Retry CFS command if needed
+                COUNT=0
+                while true; do
+                    ENABLED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/component/${TARGET_XNAME}" | jq -r '.enabled') && break
+                    let COUNT+=1
+                    if [[ ${COUNT} -gt 12 ]]; then
+                        echo "ERROR: Even after retries, command pipeline failed querying CFS component '${TARGET_XNAME}'"
+                        exit 1
+                    fi
+                    echo "WARNING: Command pipeline failed querying CFS component '${TARGET_XNAME}'. Retrying after 5 seconds."
+                    sleep 5
+                done
+                if [[ ${ENABLED} == false ]]; then
+                    echo "CFS component '${TARGET_XNAME}' still not enabled. Checking again after 30 seconds."
+                    sleep 30
+                    continue
+                elif [[ ${ENABLED} != true ]]; then
+                    echo "ERROR: Unexpected contents of 'enabled' field for CFS component '${TARGET_XNAME}': '${ENABLED}'"
+                    exit 1
+                fi
+                echo "CFS component '${TARGET_XNAME}' is enabled"
+                break
+            done
+
+            # Retry CFS command if needed
+            COUNT=0
+            while true; do
+                DESIRED_CONFIG=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/component/${TARGET_XNAME}" | jq -r '.desiredConfig') && break
+                let COUNT+=1
+                if [[ ${COUNT} -gt 12 ]]; then
+                    echo "ERROR: Even after retries, command pipeline failed querying CFS component '${TARGET_XNAME}'"
+                    exit 1
+                fi
+                echo "WARNING: Command pipeline failed querying CFS component '${TARGET_XNAME}'. Retrying after 5 seconds."
+                sleep 5
+            done
+            if [[ -z ${DESIRED_CONFIG} ]]; then
               exit 0
             fi
+            echo "Desired configuration for CFS component '${TARGET_XNAME}' is '${DESIRED_CONFIG}'"
 
             while true; do
               RESULT=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=pending" | jq length)
