CASMINST-7102: Make master node upgrade backup and update bootparameters in a sepate task with checks

diff --git a/workflows/iuf/operations/management-nodes-rollout/management-m001-rollout.yaml b/workflows/iuf/operations/management-nodes-rollout/management-m001-rollout.yaml
--- a/workflows/iuf/operations/management-nodes-rollout/management-m001-rollout.yaml
+++ b/workflows/iuf/operations/management-nodes-rollout/management-m001-rollout.yaml
@@ -1,7 +1,7 @@
 #
 # MIT License
 #
-# (C) Copyright 2022-2024 Hewlett Packard Enterprise Development LP
+# (C) Copyright 2022-2025 Hewlett Packard Enterprise Development LP
 #
 # Permission is hereby granted, free of charge, to any person obtaining a
 # copy of this software and associated documentation files (the "Software"),
@@ -81,7 +81,15 @@ spec:
                   value: "{{=jsonpath(inputs.parameters.global_params, '$.input_params.media_host')}}"
                 - name: scriptContent
                   value: |
+                    . /etc/cray/upgrade/csm/myenv
                     echo "NOTICE This workflow will rollout ncn-m001 upgrade."
+                    if [ -f /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-backup.done ] || [ -f /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-bootparameters-update.done ]; then
+                      echo "WARNING "
+                      echo "WARNING Note: To Re-run master node ncn-m001 backup, run the command: 'rm -f /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-backup.done' "
+                      echo "WARNING Note: To Re-run master node ncn-m001 bootparameters update, run the command: 'rm -f /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-bootparameters-update.done' "
+                      echo "WARNING This is not recommended and must be done only if the system is upgraded successfully and the existing backup and bootparameters update will not skip on Re-run management-m001-rollout"
+                      echo "WARNING "
+                    fi
           - name: verify-master-images-and-configuration
             dependencies:
               - INFO-to-read
@@ -110,46 +118,81 @@ spec:
                   value: 'ncn-m001'
                 - name: scriptContent
                   value: |
-                    BACKUP_TARFILE="csm_upgrade.pre_m001_reboot_artifacts.$(date +%Y%m%d_%H%M%S).tgz"
-                    ls -d \
-                        /root/apply_csm_configuration.* \
-                        /root/csm_upgrade.* \
-                        /root/output.log 2>/dev/null |
-                    sed 's_^/__' |
-                    xargs tar -C / -czvf "/root/${BACKUP_TARFILE}"
-                    cray artifacts create config-data "${BACKUP_TARFILE}" "/root/${BACKUP_TARFILE}"
-                    # Check for cray artifact create command result
-                    prepare_images_output=$(echo '{{inputs.parameters.global_params}}' | jq -r '.stage_params["prepare-images"].global["prepare-management-images"]["sat-bootprep-run"].script_stdout')
-                    CFS_CONFIG_NAME=$(echo $prepare_images_output | jq '.images | map(select(.configuration_group_names[] == "Management_Master")) | .[].configuration' | tr -d '"')
-                    IMAGE_ID=$(echo $prepare_images_output | jq '.images | map(select(.configuration_group_names[] == "Management_Master")) | .[].final_image_id' | tr -d '"')
-                    XNAME=$(cat /etc/cray/xname)
-                    # Check for the XNAME variable
-                    echo "DEBUG Setting CFS config $config on ncn-m001 ($XNAME)"
-                    /usr/share/doc/csm/scripts/operations/configuration/apply_csm_configuration.sh \
-                    --no-config-change --config-name "${CFS_CONFIG_NAME}" --xnames "${XNAME}" --no-enable --no-clear-err
-
-                    IMS_RESULTANT_IMAGE_ID=${IMAGE_ID}
-                    METAL_SERVER=$(cray bss bootparameters list --hosts "${XNAME}" --format json | jq '.[] |."params"' \
-                       | awk -F 'metal.server=' '{print $2}' \
-                       | awk -F ' ' '{print $1}')
-                    echo "${METAL_SERVER}"
-
-                    S3_ARTIFACT_PATH="boot-images/${IMS_RESULTANT_IMAGE_ID}"
-                    echo "${S3_ARTIFACT_PATH}"
-                    NEW_METAL_SERVER="s3://${S3_ARTIFACT_PATH}/rootfs"
-                    echo "${NEW_METAL_SERVER}"
-                    PARAMS=$(cray bss bootparameters list --hosts "${XNAME}" --format json | jq '.[] |."params"' | \
-                    sed "/metal.server/ s|${METAL_SERVER}|${NEW_METAL_SERVER}|" | \
-                    tr -d \")
-                    echo "${PARAMS}"
-
-                    cray bss bootparameters update --hosts "${XNAME}" \
-                        --kernel "s3://${S3_ARTIFACT_PATH}/kernel" \
-                        --initrd "s3://${S3_ARTIFACT_PATH}/initrd" \
-                        --params "${PARAMS}"
-          - name: upgrade-m001
+                    . /etc/cray/upgrade/csm/myenv
+                    if [ ! -f /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-backup.done ]; then
+                      BACKUP_TARFILE="csm_upgrade.pre_m001_reboot_artifacts.$(date +%Y%m%d_%H%M%S).tgz"
+                      ls -d \
+                          /root/apply_csm_configuration.* \
+                          /root/csm_upgrade.* \
+                          /root/output.log 2>/dev/null |
+                      sed 's_^/__' |
+                      xargs tar -C / -czvf "/root/${BACKUP_TARFILE}"
+                      cray artifacts create config-data "${BACKUP_TARFILE}" "/root/${BACKUP_TARFILE}"
+                      if [[ $? -ne 0 ]]; then
+                        echo "ERROR master node ncn-m001 backup has failed"
+                        exit 1
+                      else
+                        echo "INFO Successfully completed master node ncn-m001 backup"
+                        touch /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-backup.done
+                      fi
+                    else
+                      echo "INFO Skipping master node ncn-m001 backup.It has previously been completed"
+                    fi
+          - name: update-bootparams-m001
             dependencies:
               - backup-m001
+            templateRef:
+              name: ssh-template
+              template: shell-script
+            arguments:
+              parameters:
+                - name: dryRun
+                  value: "{{$.DryRun}}"
+                - name: mediaHost
+                  value: 'ncn-m001'
+                - name: scriptContent
+                  value: |
+                    . /etc/cray/upgrade/csm/myenv
+                    if [ ! -f /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-bootparameters-update.done ]; then
+                      prepare_images_output=$(echo '{{inputs.parameters.global_params}}' | jq -r '.stage_params["prepare-images"].global["prepare-management-images"]["sat-bootprep-run"].script_stdout')
+                      CFS_CONFIG_NAME=$(echo $prepare_images_output | jq '.images | map(select(.configuration_group_names[] == "Management_Master")) | .[].configuration' | tr -d '"')
+                      IMAGE_ID=$(echo $prepare_images_output | jq '.images | map(select(.configuration_group_names[] == "Management_Master")) | .[].final_image_id' | tr -d '"')
+                      XNAME=$(cat /etc/cray/xname)
+                      # Check for the XNAME variable
+                      echo "DEBUG Setting CFS config $config on ncn-m001 ($XNAME)"
+                      /usr/share/doc/csm/scripts/operations/configuration/apply_csm_configuration.sh \
+                      --no-config-change --config-name "${CFS_CONFIG_NAME}" --xnames "${XNAME}" --no-enable --no-clear-err
+
+                      IMS_RESULTANT_IMAGE_ID=${IMAGE_ID}
+                      METAL_SERVER=$(cray bss bootparameters list --hosts "${XNAME}" --format json | jq '.[] |."params"' \
+                        | awk -F 'metal.server=' '{print $2}' \
+                        | awk -F ' ' '{print $1}')
+                      echo "${METAL_SERVER}"
+
+                      S3_ARTIFACT_PATH="boot-images/${IMS_RESULTANT_IMAGE_ID}"
+                      echo "${S3_ARTIFACT_PATH}"
+                      NEW_METAL_SERVER="s3://${S3_ARTIFACT_PATH}/rootfs"
+                      echo "${NEW_METAL_SERVER}"
+                      PARAMS=$(cray bss bootparameters list --hosts "${XNAME}" --format json | jq '.[] |."params"' | \
+                      sed "/metal.server/ s|${METAL_SERVER}|${NEW_METAL_SERVER}|" | \
+                      tr -d \")
+                      echo "${PARAMS}"
+
+                      cray bss bootparameters update --hosts "${XNAME}" \
+                          --kernel "s3://${S3_ARTIFACT_PATH}/kernel" \
+                          --initrd "s3://${S3_ARTIFACT_PATH}/initrd" \
+                          --params "${PARAMS}"
+                      if [[ $? -ne 0 ]]; then
+                        echo "ERROR master node ncn-m001 bootparameters update has failed"
+                        exit 1
+                      else
+                        echo "INFO Successfully completed master node ncn-m001 bootparameters update" 
+                        touch /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-bootparameters-update.done
+                    else
+                      echo "INFO Skipping master node ncn-m001 bootparameters update.It has previously been completed" 
+          - name: upgrade-m001
+            dependencies:
+              - update-bootparams-m001
             templateRef:
               name: ssh-template
               template: shell-script
@@ -195,8 +238,12 @@ spec:
                         echo "ERROR libcsm-latest.noarch.rpm RPM doesn't exists under /root directory"
                         exit 1
                     fi
-                    /usr/share/doc/csm/upgrade/scripts/upgrade/ncn-upgrade-master-nodes.sh ncn-m001
 
+                    /usr/share/doc/csm/upgrade/scripts/upgrade/ncn-upgrade-master-nodes.sh ncn-m001
+                    if [[ $? -ne 0 ]]; then
+                        echo "ERROR master node ncn-m001 upgrade has failed"
+                        exit 1
+                    fi
           - name: end-operation
             dependencies:
               - upgrade-m001
