CASMINST-6208 add validation and add hostnames capability to worker rebuild workflow

diff --git a/workflows/iuf/operations/management-nodes-rollout/management-two-master-nodes-rollout.yaml b/workflows/iuf/operations/management-nodes-rollout/management-two-master-nodes-rollout.yaml
--- a/workflows/iuf/operations/management-nodes-rollout/management-two-master-nodes-rollout.yaml
+++ b/workflows/iuf/operations/management-nodes-rollout/management-two-master-nodes-rollout.yaml
@@ -64,6 +64,43 @@ spec:
             templateRef:
               name: workflow-template-record-time-template
               template: record-time-template
+          - name: verify-master-images-and-configuration
+            dependencies:
+              - start-operation
+            templateRef:
+              name: ssh-template
+              template: shell-script
+            arguments:
+              parameters:
+                - name: dryRun
+                  value: "{{$.DryRun}}"
+                - name: scriptContent
+                  value: |
+                    prepare_images_ouput=$(echo '{{inputs.parameters.global_params}}' | jq -r '.stage_params["prepare-images"].global["prepare-management-images"]["sat-bootprep-run"].script_stdout')
+
+                    # Check config exists
+                    config=$(echo $prepare_images_ouput | jq '.images | map(select(.configuration_group_names[] == "Management_Master")) | .[].configuration' | tr -d '"')
+                    if [[ -z $config ]]; then echo "ERROR  no CFS configuration was received for 'Management_Master' from prepare images stage"; exit 1; fi
+                    cray cfs configurations describe "$config" > /dev/null
+                    if [[ $? -ne 0 ]]; then
+                      exit 1 # could not find the desired cfs configuration
+                    else
+                      echo "NOTICE found CFS configuration:$config in CFS for 'Management_Master' nodes"
+                    fi
+
+                    # Check image exists
+                    image=$(echo $prepare_images_ouput | jq '.images | map(select(.configuration_group_names[] == "Management_Master")) | .[].final_image_id' | tr -d '"')
+                    if [[ -z $image ]]; then echo "ERROR  no image was received for 'Management_Master' from prepare images stage"; exit 1; fi
+                    if [[ $(echo $image | wc -l) -gt 1 ]]; then 
+                      echo "ERROR  more than 1 image was received for Management_Master nodes. Must be exactly 1 image to rebuild"
+                      echo "ERROR  Images received: $image"; exit 1
+                    fi
+                    cray ims images describe "$image" > /dev/null
+                    if [[ $? -ne 0 ]]; then
+                      exit 1 # could not find the image in IMS
+                    else
+                      echo "NOTICE found image:$image in IMS for Management_Master rebuild"
+                    fi
           - name: verify-images-and-configuration
             dependencies:
               - start-operation
@@ -137,7 +174,7 @@ spec:
                     fi
           - name: upgrade-m002
             dependencies:
-              - verify-images-and-configuration
+              - verify-master-images-and-configuration
             templateRef:
               name: ssh-template
               template: shell-script
diff --git a/workflows/iuf/operations/management-nodes-rollout/management-worker-nodes-rollout.yaml b/workflows/iuf/operations/management-nodes-rollout/management-worker-nodes-rollout.yaml
--- a/workflows/iuf/operations/management-nodes-rollout/management-worker-nodes-rollout.yaml
+++ b/workflows/iuf/operations/management-nodes-rollout/management-worker-nodes-rollout.yaml
@@ -64,6 +64,43 @@ spec:
             templateRef:
               name: workflow-template-record-time-template
               template: record-time-template
+          - name: verify-worker-images-and-configuration
+            dependencies:
+              - start-operation
+            templateRef:
+              name: ssh-template
+              template: shell-script
+            arguments:
+              parameters:
+                - name: dryRun
+                  value: "{{$.DryRun}}"
+                - name: scriptContent
+                  value: |
+                    prepare_images_ouput=$(echo '{{inputs.parameters.global_params}}' | jq -r '.stage_params["prepare-images"].global["prepare-management-images"]["sat-bootprep-run"].script_stdout')
+
+                    # Check config exists
+                    config=$(echo $prepare_images_ouput | jq '.images | map(select(.configuration_group_names[] == "Management_Worker")) | .[].configuration' | tr -d '"')
+                    if [[ -z $config ]]; then echo "ERROR  no CFS configuration was received for 'Management_Worker' from prepare images stage"; exit 1; fi
+                    cray cfs configurations describe "$config" > /dev/null
+                    if [[ $? -ne 0 ]]; then
+                      exit 1 # could not find the desired cfs configuration
+                    else
+                      echo "NOTICE found CFS configuration:$config in CFS for 'Management_Worker' nodes"
+                    fi
+
+                    # Check image exists
+                    image=$(echo $prepare_images_ouput | jq '.images | map(select(.configuration_group_names[] == "Management_Worker")) | .[].final_image_id' | tr -d '"')
+                    if [[ -z $image ]]; then echo "ERROR  no image was received for 'Management_Worker' from prepare images stage"; exit 1; fi
+                    if [[ $(echo $image | wc -l) -gt 1 ]]; then 
+                      echo "ERROR  more than 1 image was received for Management_Worker nodes. Must be exactly 1 image to rebuild"
+                      echo "ERROR  Images received: $image"; exit 1
+                    fi
+                    cray ims images describe "$image" > /dev/null
+                    if [[ $? -ne 0 ]]; then
+                      exit 1 # could not find the image in IMS
+                    else
+                      echo "NOTICE found image:$image in IMS for Management_Worker rebuild"
+                    fi
           - name: get-worker-rebuild-sets
             templateRef:
               name: ssh-template
@@ -75,42 +112,49 @@ spec:
                 - name: scriptContent
                   value: |
                     limit_management_nodes=$(echo '{{inputs.parameters.global_params}}' | jq -r '.input_params.limit_management_nodes[]')
+                    percent_rollout=$(echo '{{inputs.parameters.global_params}}' | jq -r '.input_params.concurrent_management_rollout_percentage')
+                    total_worker_nodes=$(kubectl get node --selector='!node-role.kubernetes.io/master' --no-headers=true | awk '{print $1}' | tr "\n", " ")
+                    array_total_worker_nodes=($total_worker_nodes)
+                    num_total_worker_nodes=${#array_total_worker_nodes[@]}
+
+                    # set the number of worker nodes that should be rebuilt concurrently
+                    workers_per_set=$(( $(( percent_rollout * num_total_worker_nodes )) / 100 ))
+                    if [[ $workers_per_set -eq 0 ]]; then
+                      workers_per_set=1
+                    fi
+
+                    # get workers to rebuild
                     if [[ -n $(echo $limit_management_nodes | grep 'Management_Worker') ]]; then
-                      worker_nodes=$(kubectl get node --selector='!node-role.kubernetes.io/master' --no-headers=true | awk '{print $1}' | tr "\n", " ")
+                      worker_nodes_to_rebuild=$(kubectl get node --selector='!node-role.kubernetes.io/master' --no-headers=true | awk '{print $1}' | tr "\n", " ")
                       labeled_workers=$(kubectl get nodes --selector='iuf-prevent-rollout=true' -o jsonpath='{range .items[*]}{@.metadata.name}{" "}')
                       for labeled_worker in $labeled_workers; do
-                        worker_nodes=$(echo $worker_nodes | sed s/"$labeled_worker"//)
+                        worker_nodes_to_rebuild=$(echo $worker_nodes_to_rebuild | sed s/"$labeled_worker"//)
                       done
-
-                      # split nodes into sets to rebuild
-                      percent_rollout=$(echo '{{inputs.parameters.global_params}}' | jq -r '.input_params.concurrent_management_rollout_percentage')
-                      number_of_sets=$((100 / $percent_rollout))
-                      if [[ $percent_rollout -lt 100 ]] && [[ $number_of_sets -lt 2 ]]; then
-                        number_of_sets=2   # if 100% is not specified, we do not want only 1 set
-                      fi
-                      array_nodes_to_rebuild=($worker_nodes)
-                      num_nodes_to_rebuild=${#array_nodes_to_rebuild[@]}
-                      rebuild_set_size=$(( $num_nodes_to_rebuild / $number_of_sets ))
-                      if [[ $rebuild_set_size -eq 0 ]]; then rebuild_set_size=1; fi
-                      index=0
-                      set=""
-                      output=""
-                      for node in $worker_nodes; do
-                        index=$(( $index + 1 ))
-                        set="${set},""$node"
-                        if [[ $index -eq $rebuild_set_size ]]; then
-                          output="${output} ${set#?}"
-                          index=0
-                          set=""
-                        fi
-                      done
-                      if [[ -n $set ]]; then
-                        output="${output} ${set#?}"
-                      fi
-                      echo "${output#?}"
                     else
-                      echo 'none'
+                      # rebuild worker nodes specified by hostnames
+                      worker_nodes_to_rebuild="${limit_management_nodes}"
+                      labeled_workers=$(kubectl get nodes --selector='iuf-prevent-rollout=true' -o jsonpath='{range .items[*]}{@.metadata.name}{" "}')
+                      for labeled_worker in $labeled_workers; do
+                        worker_nodes_to_rebuild=$(echo $worker_nodes_to_rebuild | sed s/"$labeled_worker"//)
+                      done
                     fi
+
+                    index=0
+                    set=""
+                    output=""
+                    for node in $worker_nodes_to_rebuild; do
+                      index=$(( index + 1 ))
+                      set="${set},${node}"
+                      if [[ $index -eq $workers_per_set ]]; then
+                        output="${output} ${set#?}"
+                        index=0
+                        set=""
+                      fi
+                    done
+                    if [[ -n ${set} ]]; then
+                      output="${output} ${set#?}"
+                    fi
+                    echo "${output#?}"
           - name: process-worker-rebuild-sets
             dependencies:
               - get-worker-rebuild-sets
@@ -169,11 +213,6 @@ spec:
                 value: "{{$.DryRun}}"
               - name: scriptContent
                 value: |
-                  limit_management_nodes=$(echo '{{inputs.parameters.global_params}}' | jq -r '.input_params.limit_management_nodes[]')
-                  if [[ -z $(echo $limit_management_nodes | grep 'Management_Worker') ]]; then
-                    echo "NOTICE  Not rebuilding worker nodes because 'Management_Worker' was not in --limit-management-rollout"
-                    exit 0
-                  fi
                   sets="{{inputs.parameters.sets}}"
                   set_array=($sets)
                   current_count="{{inputs.parameters.counter}}"
