CASMTRIAGE-8281: remove task remove-previous-done-files in process-media and add in CSM hook as they are specific to CSM Upgrade

diff --git a/workflows/iuf/operations/management-nodes-rollout/management-m001-rollout.yaml b/workflows/iuf/operations/management-nodes-rollout/management-m001-rollout.yaml
--- a/workflows/iuf/operations/management-nodes-rollout/management-m001-rollout.yaml
+++ b/workflows/iuf/operations/management-nodes-rollout/management-m001-rollout.yaml
@@ -110,8 +110,7 @@ spec:
                   value: 'ncn-m001'
                 - name: scriptContent
                   value: |
-                    . /etc/cray/upgrade/csm/myenv
-                    if [ ! -f /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-backup.done ]; then
+                    if [ ! -f /etc/cray/upgrade/csm/iuf/ncn-m001-bootparameters-update.done ]; then
                       BACKUP_TARFILE="csm_upgrade.pre_m001_reboot_artifacts.$(date +%Y%m%d_%H%M%S).tgz"
                       ls -d \
                           /root/apply_csm_configuration.* \
@@ -120,33 +119,13 @@ spec:
                       sed 's_^/__' |
                       xargs tar -C / -czvf "/root/${BACKUP_TARFILE}"
                       cray artifacts create config-data "${BACKUP_TARFILE}" "/root/${BACKUP_TARFILE}"
+                      # Check for cray artifact create command result
                       if [[ $? -ne 0 ]]; then
                         echo "ERROR master node ncn-m001 backup has failed"
                         exit 1
                       else
                         echo "INFO Successfully completed master node ncn-m001 backup"
-                        touch /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-backup.done
                       fi
-                    else
-                      echo "INFO Skipping master node ncn-m001 backup. It has previously been completed"
-                      echo "INFO Note: To Re-run master node ncn-m001 backup, run the command: 'rm -f /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-backup.done' "
-                    fi
-          - name: update-bootparams-m001
-            dependencies:
-              - backup-m001
-            templateRef:
-              name: ssh-template
-              template: shell-script
-            arguments:
-              parameters:
-                - name: dryRun
-                  value: "{{$.DryRun}}"
-                - name: mediaHost
-                  value: 'ncn-m001'
-                - name: scriptContent
-                  value: |
-                    . /etc/cray/upgrade/csm/myenv
-                    if [ ! -f /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-bootparameters-update.done ]; then
                       prepare_images_output=$(echo '{{inputs.parameters.global_params}}' | jq -r '.stage_params["prepare-images"].global["prepare-management-images"]["sat-bootprep-run"].script_stdout')
                       CFS_CONFIG_NAME=$(echo $prepare_images_output | jq '.images | map(select(.configuration_group_names[] == "Management_Master")) | .[].configuration' | tr -d '"')
                       IMAGE_ID=$(echo $prepare_images_output | jq '.images | map(select(.configuration_group_names[] == "Management_Master")) | .[].final_image_id' | tr -d '"')
@@ -180,15 +159,19 @@ spec:
                         exit 1
                       else
                         echo "INFO Successfully completed master node ncn-m001 bootparameters update" 
-                        touch /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-bootparameters-update.done
+                        touch /etc/cray/upgrade/csm/iuf/ncn-m001-bootparameters-update.done
                       fi
                     else
-                      echo "INFO Skipping master node ncn-m001 bootparameters update. It has previously been completed"
-                      echo "INFO Note: To Re-run master node ncn-m001 bootparameters update, run the command: 'rm -f /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-bootparameters-update.done' "
+                      echo "WARNING "
+                      echo "WARNING Note: master node ncn-m001 has not been successfully upgraded during previous run." 
+                      echo "WARNING To Re-run ncn-m001 upgrade, run the command: 'rm -f ncn-m001-bootparameters-update.done' "
+                      echo "WARNING This should be done only if the conditions causing upgrade failure during previous run has been fixed."
+                      echo "WARNING "
+                      exit 1
                     fi
           - name: upgrade-m001
             dependencies:
-              - update-bootparams-m001
+              - backup-m001
             templateRef:
               name: ssh-template
               template: shell-script
@@ -240,9 +223,7 @@ spec:
                         echo "ERROR master node ncn-m001 upgrade has failed"
                         exit 1
                     else
-                        . /etc/cray/upgrade/csm/myenv
-                        rm /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-backup.done
-                        rm /etc/cray/upgrade/csm/${CSM_REL_NAME}/ncn-m001-bootparameters-update.done
+                        rm /etc/cray/upgrade/csm/iuf/ncn-m001-bootparameters-update.done
                     fi
           - name: end-operation
             dependencies:
