CASM-4137 Improving iuf messages for management-nodes-rollout stage (#3813)
* CASM-4137 Improving iuf messages for management-nodes-rollout stage

* CASM-4137 Addressing review comments

diff --git a/workflows/iuf/operations/management-nodes-rollout/verify-images-and-configuration.yaml b/workflows/iuf/operations/management-nodes-rollout/verify-images-and-configuration.yaml
--- a/workflows/iuf/operations/management-nodes-rollout/verify-images-and-configuration.yaml
+++ b/workflows/iuf/operations/management-nodes-rollout/verify-images-and-configuration.yaml
@@ -80,57 +80,76 @@ spec:
                     if [[ -n $(echo $limit_management_nodes | grep 'Management_Worker') ]]; then rebuild_workers=true; fi
                     if [[ -n $(echo $limit_management_nodes | grep 'Management_Master') ]]; then rebuild_masters=true; fi
 
-                    prepare_images_ouput=$(echo '{{inputs.parameters.global_params}}' | jq -r '.stage_params["prepare-images"].global["prepare-management-images"]["sat-bootprep-run"].script_stdout')
+                    prepare_images_output=$(echo '{{inputs.parameters.global_params}}' | jq -r '.stage_params["prepare-images"].global["prepare-management-images"]["sat-bootprep-run"].script_stdout')
 
                     if $rebuild_workers; then
                       # Check config exists
-                      config=$(echo $prepare_images_ouput | jq '.images | map(select(.configuration_group_names[] == "Management_Worker")) | .[].configuration' | tr -d '"')
-                      if [[ -z $config ]]; then echo "ERROR  no CFS configuration was received for 'Management_Worker' from prepare images stage"; exit 1; fi
-                      cray cfs configurations describe "$config" > /dev/null
+                      config=$(echo $prepare_images_output | jq '.images | map(select(.configuration_group_names[] == "Management_Worker")) | .[].configuration' | tr -d '"')
+                      if [[ -z $config ]]; then
+                        echo "ERROR No CFS configuration was received for 'Management_Worker' from 'prepare-images' stage. Retry by running from 'prepare-images' stage"
+                        exit 1
+                      fi
+                      result=$(cray cfs configurations describe "$config" 2>&1)
                       if [[ $? -ne 0 ]]; then
-                        exit 1 # could not find the desired cfs configuration
+                        result=$(echo "$result" | sed -e 's/^/DEBUG /')
+                        echo "ERROR Could not find the desired configuration $configuration in CFS for Management_Worker nodes"
+                        echo -e "DEBUG Command <cray cfs configurations describe $configuration> produced -\n\n$result"
+                        exit 1
                       else
-                        echo "NOTICE found CFS configuration:$config in CFS for 'Management_Worker' nodes"
+                        echo "DEBUG Found CFS configuration:$config in CFS for Management_Worker nodes"
                       fi
 
                       # Check image exists
-                      image=$(echo $prepare_images_ouput | jq '.images | map(select(.configuration_group_names[] == "Management_Worker")) | .[].final_image_id' | tr -d '"')
-                      if [[ -z $image ]]; then echo "ERROR  no image was received for 'Management_Worker' from prepare images stage"; exit 1; fi
-                      if [[ $(echo $image | wc -l) -gt 1 ]]; then 
-                        echo "ERROR  more than 1 image was received for Management_Worker nodes. Must be exactly 1 image to rebuild"
-                        echo "ERROR  Images received: $image"; exit 1
+                      image=$(echo $prepare_images_output | jq '.images | map(select(.configuration_group_names[] == "Management_Worker")) | .[].final_image_id' | tr -d '"')
+                      if [[ -z $image ]]; then
+                        echo "ERROR No image was received for 'Management_Worker' from 'prepare-images' stage. Retry by running from 'prepare-images' stage"
+                        exit 1
                       fi
-                      cray ims images describe "$image" > /dev/null
+                      if [[ $(echo $image | wc -l) -gt 1 ]]; then 
+                        echo "ERROR More than 1 image was received for Management_Worker nodes. Must be exactly 1 image to rebuild"
+                        echo "ERROR Images received: $image"
+                        exit 1
+                      fi
+                      result=$(cray ims images describe "$image" 2>&1)
                       if [[ $? -ne 0 ]]; then
-                        exit 1 # could not find the image in IMS
+                        result=$(echo "$result" | sed -e 's/^/DEBUG /')
+                        echo "ERROR Could not find the required image $image in IMS for Management_Worker rebuild"
+                        echo -e "DEBUG Command <cray ims images describe $image> produced -\n\n$result"
+                        exit 1
                       else
-                        echo "NOTICE found image:$image in IMS for Management_Worker rebuild"
+                        echo "DEBUG Found image:$image in IMS for Management_Worker rebuild"
                       fi
                     fi
 
                     if $rebuild_masters; then
                       # Check config exists
-                      config=$(echo $prepare_images_ouput | jq '.images | map(select(.configuration_group_names[] == "Management_Master")) | .[].configuration' | tr -d '"')
-                      if [[ -z $config ]]; then echo "ERROR  no CFS configuration was received for 'Management_Master' from prepare images stage"; exit 1; fi
-                      cray cfs configurations describe "$config" > /dev/null
+                      config=$(echo $prepare_images_output | jq '.images | map(select(.configuration_group_names[] == "Management_Master")) | .[].configuration' | tr -d '"')
+                      if [[ -z $config ]]; then echo "ERROR No CFS configuration was received for 'Management_Master' from 'prepare-images' stage"; exit 1; fi
+                      result=$(cray cfs configurations describe "$config" 2>&1)
                       if [[ $? -ne 0 ]]; then
-                        exit 1 # could not find the desired cfs configuration
+                        result=$(echo "$result" | sed -e 's/^/DEBUG /')
+                        echo "ERROR Could not find the desired configuration $configuration in CFS for Management_Master nodes"
+                        echo -e "DEBUG Command <cray cfs configurations describe $configuration> produced -\n\n$result"
+                        exit 1
                       else
-                        echo "NOTICE found CFS configuration:$config in CFS for 'Management_Master' nodes"
+                        echo "DEBUG Found CFS configuration:$config in CFS for Management_Master nodes"
                       fi
 
                       # Check image exists
-                      image=$(echo $prepare_images_ouput | jq '.images | map(select(.configuration_group_names[] == "Management_Master")) | .[].final_image_id' | tr -d '"')
-                      if [[ -z $image ]]; then echo "ERROR  no image was received for 'Management_Master' from prepare images stage"; exit 1; fi
+                      image=$(echo $prepare_images_output | jq '.images | map(select(.configuration_group_names[] == "Management_Master")) | .[].final_image_id' | tr -d '"')
+                      if [[ -z $image ]]; then echo "ERROR No image was received for 'Management_Master' from prepare images stage"; exit 1; fi
                       if [[ $(echo $image | wc -l) -gt 1 ]]; then 
-                        echo "ERROR  more than 1 image was received for Management_Master nodes. Must be exactly 1 image to rebuild"
-                        echo "ERROR  Images received: $image"; exit 1
+                        echo "ERROR More than 1 image was received for Management_Master nodes. Must be exactly 1 image to rebuild"
+                        echo "ERROR Images received: $image"; exit 1
                       fi
-                      cray ims images describe "$image" > /dev/null
+                      result=$(cray ims images describe "$image" 2>&1)
                       if [[ $? -ne 0 ]]; then
-                        exit 1 # could not find the image in IMS
+                        result=$(echo "$result" | sed -e 's/^/DEBUG /')
+                        echo "ERROR Could not find the required image $image in IMS for Management_Master rebuild"
+                        echo -e "DEBUG Command <cray ims images describe $image> produced -\n\n$result"
+                        exit 1
                       else
-                        echo "NOTICE found image:$image in IMS for Management_Master rebuild"
+                        echo "DEBUG Found image:$image in IMS for Management_Master rebuild"
                       fi
                     fi
           - name: end-operation
