CASMPET-6348 local testing changes

diff --git a/workflows/storage-backup/storage.drain.yaml b/workflows/storage-backup/storage.drain.yaml
--- a/workflows/storage-backup/storage.drain.yaml
+++ b/workflows/storage-backup/storage.drain.yaml
@@ -24,19 +24,17 @@
 apiVersion: argoproj.io/v1alpha1
 kind: WorkflowTemplate
 metadata:
-  name: add-storage-node-to-haproxy-keepalived
+  name: storage-node-drain
   namespace: argo
 spec:
-  entrypoint: main
   templates:
     - name: main
       inputs:
-        parameters:
-          - name: upgradeType
-          - name: targetNcn
+        - name: targetNcn
+        - name: dryRun
       dag:
         tasks:
-          - name: copy-k8s-admin-config
+          - name: drain
             templateRef:
               name: ssh-template
               template: shell-script
@@ -47,12 +45,26 @@ spec:
                 - name: scriptContent
                   value: |
                     TARGET_NCN="{{inputs.parameters.targetNcn}}"
-                    if [[ ${TARGET_NCN} =~ ncn-s00[1-3] ]]; then
-                        scp /etc/kubernetes/admin.conf ${TARGET_NCN}:/etc/kubernetes
-                        echo "Reconfiguring ceph-csi storage class config map"
-                        ssh ${TARGET_NCN} 'source /srv/cray/scripts/common/csi-configuration.sh; create_k8s_storage_class'
+                    ceph orch host drain $TARGET_NCN
+                    int=0
+                    success=0
+                    while [[ $int -lt 100 ]]; do
+                      if [[ $(ceph orch ps $TARGET_NCN | grep "osd" | wc -l) -eq 0 ]]; then
+                        success=1
+                        break
+                      else
+                        echo "Waiting for all osds to be removed from $TARGET_NCN. Sleeping 20s..."
+                        sleep 20
+                      fi
+                      int=$(($int + 1))
+                    done
+                    if [[ $success -eq 0 ]]; then
+                      echo "ERROR did not successfully drain osds from $TARGET_NCN. Manually run 'ceph orch ps $TARGET_NCN' to see what is still running."
+                      exit 1
                     fi
-          - name: add-storage-node-to-haproxy-keepalived
+          - name: fail-over-mds
+            dependencies: 
+              - drain
             templateRef:
               name: ssh-template
               template: shell-script
@@ -63,17 +75,16 @@ spec:
                 - name: scriptContent
                   value: |
                     TARGET_NCN="{{inputs.parameters.targetNcn}}"
-                    ssh $TARGET_NCN \
-                      'source /srv/cray/scripts/metal/update_apparmor.sh
-                      reconfigure-apparmor; /srv/cray/scripts/metal/generate_haproxy_cfg.sh > /etc/haproxy/haproxy.cfg
-                      systemctl enable haproxy.service
-                      systemctl restart haproxy.service
-                      /srv/cray/scripts/metal/generate_keepalived_conf.sh > /etc/keepalived/keepalived.conf
-                      systemctl enable keepalived.service
-                      systemctl restart keepalived.service'
-          - name: restart-services
-            dependencies:
-              - add-storage-node-to-haproxy-keepalived
+                    echo "This will fail over mds if the active cephfs or admin-tool mds daemon is on $TARGET_NCN"
+                    active_mds=$(ceph fs status -f json-pretty|jq -r '.mdsmap[]|select(.state=="active")|.name')
+                    for each in $active_mds; do
+                      if [[ -n $(echo $each | grep $TARGET_NCN ) ]]; then
+                        ceph mds fail $each
+                      fi
+                    done
+          - name: fail-over-mgr
+            dependencies: 
+              - drain
             templateRef:
               name: ssh-template
               template: shell-script
@@ -84,13 +95,10 @@ spec:
                 - name: scriptContent
                   value: |
                     TARGET_NCN="{{inputs.parameters.targetNcn}}"
-                    echo "Enabling Ceph services to start on boot and starting if stopped"
-                    ssh $TARGET_NCN \
-                       'for service in $(cephadm ls |jq -r .[].systemd_unit|grep $(ceph status -f json-pretty |jq -r .fsid));
-                        do
-                          systemctl enable $service
-                          if [[ $(systemctl is-active $service) != "active" ]]
-                          then
-                            systemctl restart $service
-                          fi
-                        done'
+                    echo "This will fail over mgr if the active mgr is on $TARGET_NCN"
+                    active_mgr=$(ceph mgr dump | jq -r .active_name)
+                    echo "Acitve mgr is $active_mgr"
+                    if [[ -n $(echo $active_mgr | grep $TARGET_NCN) ]]; then
+                      ceph mgr fail
+                      echo "Failed over mgr"
+                    fi
