CASMPET-5760: Add network policy stashing and move restart-ds inline

diff --git a/workflows/templates/cilium.migrate.yaml b/workflows/templates/cilium.migrate.yaml
--- a/workflows/templates/cilium.migrate.yaml
+++ b/workflows/templates/cilium.migrate.yaml
@@ -99,7 +99,13 @@ spec:
               - name: scriptContent
                 value: |
                   echo "restarting daemonsets on {{inputs.parameters.targetNcn}}"
-                  /srv/cray/scripts/common/restart-ds.sh {{inputs.parameters.targetNcn}}
+                  NODE={{inputs.parameters.targetNcn}}
+                  kubectl get nodes --no-headers=true | awk '{print $1}' | grep -q "^${NODE}$" || { echo "ERROR: Invalid node name ${NODE}"; exit 1; }
+
+                  while read -r a b; do
+                    echo "Restarting pod $b"
+                    kubectl -n $a delete pod $b
+                  done < <(kubectl get pods -A -o json | jq -j --arg n "$NODE" '.items[] | select (.spec.nodeName==$n) | select(.spec.hostNetwork!=true) |.metadata.namespace, " ", .metadata.name, "\n"')
         - name: uncordon 
           dependencies:
             - restart-daemonsets 
