CASMPET-5760: Fix missing quote (#4502)

diff --git a/workflows/templates/cilium.migrate.yaml b/workflows/templates/cilium.migrate.yaml
--- a/workflows/templates/cilium.migrate.yaml
+++ b/workflows/templates/cilium.migrate.yaml
@@ -100,7 +100,7 @@ spec:
                 value: |
                   echo "restarting daemonsets on {{inputs.parameters.targetNcn}}"
                   NODE={{inputs.parameters.targetNcn}}
-                  kubectl get node ${NODE} >/dev/null 2>&1 || { echo "Error: Invalid node name ${NODE}; exit 1; }
+                  kubectl get node ${NODE} >/dev/null 2>&1 || { echo "Error: Invalid node name ${NODE}"; exit 1; }
 
                   while read -r ns pod; do
                     echo "Restarting pod $pod"
