Revert "CASMINST-5657 Add common WorkflowTemplate to sync secret to Argo name…"
This reverts commit 853e4270c6dd5af2357564b99ff76ce9d0249956.

diff --git a/workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml b/workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml
--- a/workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml
+++ b/workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml
@@ -60,9 +60,7 @@ spec:
           name: workflow-template-record-time-template
           template: record-time-template
     - - name: nexus-get-prerequisites
-        templateRef:
-          name: nexus-get-prerequisites-template
-          template: nexus-get-prerequisites
+        template: nexus-get-prerequisites-template
         arguments:
           parameters:
           - name: global_params
@@ -70,10 +68,8 @@ spec:
     - - name: nexus-rpm-load
         template: nexus-rpm-load-template
         hooks:
-          exit:
-            templateRef:
-              name: cleanup-nexus-admin-credential-template
-              template: cleanup-nexus-admin-credential
+          exit: 
+            template: cleanup-template
             arguments:
               parameters:
               - name: nexus_admin_credential_secret_name
@@ -144,6 +140,102 @@ spec:
       args: ["DIFF_TIME=$(expr {{inputs.parameters.opend}} - {{inputs.parameters.opstart}}); echo $DIFF_TIME; echo $DIFF_TIME > /tmp/diff_time.txt"]
 
 ### Templates ###
+## nexus-get-prerequisites-template ##
+  - name: nexus-get-prerequisites-template
+    tolerations:
+    - key: node-role.kubernetes.io/master
+      effect: NoSchedule
+    - key: node-role.kubernetes.io/control-plane
+      effect: NoSchedule
+    metadata:
+      annotations:
+        sidecar.istio.io/inject: "false"
+    inputs:
+      parameters:
+      - name: global_params
+    outputs:
+      parameters:
+        - name: secret_name
+          valueFrom:
+            path: /tmp/secret_name
+        - name: current_product_manifest
+          valueFrom:
+            path: /tmp/current_product_manifest
+        - name: product_directory
+          valueFrom:
+            path: /tmp/product_directory
+    retryStrategy:
+        limit: "2"
+        retryPolicy: "Always"
+        backoff:
+          duration: "10s" # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
+          factor: "2"
+          maxDuration: "1m"
+    script:
+      # TBD: This is a repeated function. Can this change to a reference?
+      image: artifactory.algol60.net/csm-docker/stable/docker.io/portainer/kubectl-shell:latest-v1.21.1-amd64
+      command: [bash]
+      source: |
+        function sync_item() {
+          item_name="$1"
+          source_ns="$2"
+          destination_name="$3-$RANDOM"
+          destination_ns="$4"
+          result=$(kubectl get $item_name -n $source_ns 2>&1)
+          if [ $? -eq 0 ]; then
+            echo "DEBUG Syncing $item_name from $source_ns to $destination_ns as $destination_name"
+            kubectl get $item_name -n $source_ns -o json | \
+              jq 'del(.metadata.namespace)' | \
+              jq 'del(.metadata.creationTimestamp)' | \
+              jq 'del(.metadata.resourceVersion)' | \
+              jq 'del(.metadata.selfLink)' | \
+              jq 'del(.metadata.uid)' | \
+              jq 'del(.metadata.ownerReferences)' | \
+              jq 'del(.metadata.name)' | \
+              jq '.metadata |= . + {"name":"'$destination_name'"}' | \
+              kubectl apply -n $destination_ns -f -
+              rc=$?
+              if [ $rc -ne 0 ]; then
+                echo "ERROR Failed to create secret $destination_name in $destination_ns namespace from $item_name in $source_ns namespace"
+              fi
+              return $rc
+          else
+            echo "ERROR $item_name not found in $source_ns namespace"
+            result=$(echo "$result" | sed -e 's/^/DEBUG /')
+            echo -e "DEBUG <kubectl get $item_name -n $source_ns> failed with\n\n$result"
+            return 1
+          fi
+        }
+        err=0
+        sync_item secret/nexus-admin-credential nexus nexus-admin-credential-argo argo
+        if [ $? -ne 0 ]; then
+          err=1
+        fi
+        echo $destination_name > /tmp/secret_name
+
+        # Retrieve the content of the current product manifest as json.
+        product_name={{inputs.parameters.global_params}} | jq -r '.product_manifest.current_product.name'
+        echo "DEBUG Fetching the product manifest for $product_name"
+        cat <<EOF | jq '.product_manifest.current_product.manifest.content' > /tmp/current_product_manifest
+          {{inputs.parameters.global_params}}
+        EOF
+        if [ $? -ne 0 ]; then
+          err=1
+          echo "ERROR Failed to fetch product manifest for $product_name. Rerun with valid product tarball from 'process-media' stage"
+        fi
+
+        # Retrieve the product directory.
+        echo "DEBUG Retrieving the product directory for $product_name"
+        cat <<EOF | jq -r '.product_manifest.current_product.original_location' > /tmp/product_directory
+          {{inputs.parameters.global_params}}
+        EOF
+        if [ $? -ne 0 ]; then
+          echo "ERROR Failed to fetch product directory for $product_name. Rerun with valid product tarball from 'process-media' stage"
+          err=1
+        fi
+
+        # Exit with an error if we had any.
+        exit $err
 ## nexus-rpm-load-template ##
   - name: nexus-rpm-load-template
     inputs:
@@ -185,3 +277,30 @@ spec:
     - name: product
       hostPath:
         path: "{{inputs.parameters.product_directory}}"
+## cleanup-template ##
+## Remove the secret created earlier.
+# TBD: This is a repeated function. Can this change to a reference?
+  - name: cleanup-template
+    inputs:
+      parameters:
+      - name: nexus_admin_credential_secret_name
+    tolerations:
+    - key: node-role.kubernetes.io/master
+      effect: NoSchedule
+    - key: node-role.kubernetes.io/control-plane
+      effect: NoSchedule
+    metadata:
+      annotations:
+        sidecar.istio.io/inject: "false"
+    script:
+      image: artifactory.algol60.net/csm-docker/stable/docker.io/portainer/kubectl-shell:latest-v1.21.1-amd64
+      command: [bash]
+      source: |
+        nexus_secret_name={{inputs.parameters.nexus_admin_credential_secret_name}}
+        echo "DEBUG Deleting secret $nexus_secret_name from argo workspace"
+        result=$(kubectl -n argo delete secret/$nexus_secret_name 2>&1)
+        if [ $? -ne 0 ]; then
+          result=$(echo "$result" | sed -e 's/^/DEBUG /')
+          echo "ERROR Deleting secret $nexus_secret_name failed in argo namespace"
+          echo -e "DEBUG <kubectl -n argo delete secret/$nexus_secret_name> failed with\n\n$result"
+        fi
