CASMPET-6738: handle multiple ipxe pods (#4113)
(cherry picked from commit 083f5366bbcd0ed850ebba500bbd14bb2bb12ea9)

Co-authored-by: Bo Quan <bo.quan@hpe.com>

diff --git a/workflows/ncn/hooks/before-all/move-critical-singleton-pods.yaml b/workflows/ncn/hooks/before-all/move-critical-singleton-pods.yaml
--- a/workflows/ncn/hooks/before-all/move-critical-singleton-pods.yaml
+++ b/workflows/ncn/hooks/before-all/move-critical-singleton-pods.yaml
@@ -52,25 +52,31 @@ spec:
 
     echo
 
-    criticalPodLabels=( "app=nexus" "app.kubernetes.io/name=cray-ipxe-x86-64" "app.kubernetes.io/name=cray-dhcp-kea" "app.kubernetes.io/name=cray-cfs-api-db" )
+    criticalPodLabels=( "app=nexus" "app.kubernetes.io/instance=cms-ipxe" "app.kubernetes.io/name=cray-dhcp-kea" "app.kubernetes.io/name=cray-cfs-api-db" )
     for label in ${criticalPodLabels[@]};do
       pods=($(kubectl get pods -A -l ${label} -o custom-columns=:.metadata.name))
-      # we may have multiple pods matched with the label
-      # log error and exit on matching multiple pods
-      if [[ ${#pods[@]} -ne 1 ]]; then
-        echo "ERROR: label: ${label} matches zero/multiple pods"
+      if [[ ${#pods[@]} -eq 0 ]]; then
+        # At least one pod should be found for each label
+        echo "ERROR: no pods are found with label: ${label}"
+        exit 1
+      elif [[ ${#pods[@]} -ne 1 && ${pods[0]} != *"ipxe"* ]]; then
+        # Only app.kubernetes.io/instance=cms-ipxe label can match more than 1 ipxe pods (CASMPET-6738)
+        echo "ERROR: multiple pods are found with label: ${label}"
         exit 1
       fi
-      podName=${pods[0]}
-      currentNode=$(kubectl get po -A -o wide | grep $podName | awk '{print $8}')
-      ns=$(kubectl get po -A | grep $podName | awk '{print $1}')
-      if [[ $targetNcns != *$currentNode* ]]; then
-        echo "$podName is on $currentNode and that node is not being rebuilt by this workflow. Not moving $podName."
-      elif [[ "$nodeMoveTo" != "$currentNode" ]]; then
-        echo "Move Pod: $podName to Node: $nodeMoveTo"
-        /opt/cray/platform-utils/move_pod.sh $podName $nodeMoveTo > /dev/null
-      fi
 
-      kubectl wait --for=condition=ready pod -l ${label} -n $ns --timeout=5m
+      for podName in "${pods[@]}"
+      do
+        currentNode=$(kubectl get po -A -o wide | grep $podName | awk '{print $8}')
+        ns=$(kubectl get po -A | grep $podName | awk '{print $1}')
+        if [[ $targetNcns != *$currentNode* ]]; then
+          echo "$podName is on $currentNode and that node is not being rebuilt by this workflow. Not moving $podName."
+        elif [[ "$nodeMoveTo" != "$currentNode" ]]; then
+          echo "Move Pod: $podName to Node: $nodeMoveTo"
+          /opt/cray/platform-utils/move_pod.sh $podName $nodeMoveTo > /dev/null
+        fi
+
+        kubectl wait --for=condition=ready pod -l ${label} -n $ns --timeout=5m
+      done
     done
   templateRefName: ssh-template
