CASM-3946 Enhancing IUF template messages for 3 stages:process-media/pre-install-check/deliver-product

diff --git a/workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml b/workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml
--- a/workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml
+++ b/workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml
@@ -73,21 +73,26 @@ spec:
                 PRODUCT=$(echo '{{inputs.parameters.global_params}}' | jq -r '.product_manifest.current_product.manifest.name')
 
                 if [[ "${CONTENT,,}" == "null" ]] || [[ "$CONTENT" == "" ]]; then
-                    echo "ERROR current_product.manifest is null or empty"
+                    echo "ERROR Product manifest is null or empty"
                     exit 1
                 fi
 
                 if [[ "${PARENT_DIR,,}" == "null" ]] || [[ "$PARENT_DIR" == "" ]]; then
-                    echo "ERROR current_product.parent_directory is null or empty"
+                    echo "ERROR Extracted tarball directory is null or empty"
                     exit 1
                 fi
 
                 if [[ "${PRODUCT,,}" == "null" ]] || [[ "$PRODUCT" == "" ]]; then
-                    echo "ERROR current_product.manifest.name is null or empty"
+                    echo "ERROR Product name is null or empty from the product manifest"
                     exit 1
                 fi
 
+                echo "INFO Loftsman uploading manifest for $PRODUCT from $PARENT_DIR"
                 /usr/local/bin/loftsman-manifest-upload "$CONTENT" "$PARENT_DIR" "$PRODUCT"
+                if [ $? -ne 0 ]; then
+                  echo "ERROR Loftsman manifest upload failed for $PRODUCT from $PARENT_DIR"
+                  exit 1
+                fi
 
     - - name: loftsman-update-product-catalog
         templateRef:
diff --git a/workflows/iuf/operations/preflight-checks-for-services.yaml b/workflows/iuf/operations/preflight-checks-for-services.yaml
--- a/workflows/iuf/operations/preflight-checks-for-services.yaml
+++ b/workflows/iuf/operations/preflight-checks-for-services.yaml
@@ -77,58 +77,69 @@ spec:
                   value: |
                     error_flag=0
 
-                    # check s3 
-                    if ! cray artifacts list boot-images > /dev/null; then
-                      echo "ERROR s3 is not operational."
+                    # check s3
+                    image_list_output=$(cray artifacts list boot-images 2>&1)
+                    if [ $? -ne 0 ]; then
+                      echo "ERROR s3 is not operational"
+                      echo "ERROR <cray artifacts list boot-images> failed with -"
+                      echo "$image_list_output" | sed -e 's/^/ERROR /'
                       error_flag=1
                     else
-                      echo "INFO s3 is operational."
+                      echo "INFO s3 is operational"
                     fi
                     
                     # check CFS
-                    if ! cray cfs options list > /dev/null; then
-                      echo "ERROR CFS is not operational."
-                      error_flag=1
+                    cfs_list_output=$(cray cfs options list 2>&1)
+                    if [ $? -ne 0 ]; then
+                      echo "ERROR CFS is not operational"
+                      echo "ERROR <cray cfs options list> failed with -"
+                      echo "$cfs_list_output" | sed -e 's/^/ERROR /'
+                     error_flag=1
                     else
-                      echo "INFO CFS is operational."
+                      echo "INFO CFS is operational"
                     fi
                     
                     # check gitea VCS
                     vcs_user=$(kubectl get secret -n services vcs-user-credentials --template={{.data.vcs_username}} | base64 --decode)
                     vcs_pass=$(kubectl get secret -n services vcs-user-credentials --template={{.data.vcs_password}} | base64 --decode)
-                    vcs_vers=$(curl -s https://api-gw-service-nmn.local/vcs/api/v1/version -u ${vcs_user}:${vcs_pass} | jq -r '. | .version')
+                    vcs_vers=$(curl -s https://api-gw-service-nmn.local/vcs/api/v1/version -u ${vcs_user}:${vcs_pass} | jq -r '. | .version' 2>&1)
 
                     if [[ -z $vcs_vers ]]; then
-                      echo "ERROR VCS is not operational. This check will fail if VCS is unable to return the api version."
+                      echo "ERROR VCS is not operational. This check failed since VCS is unable to return its api version with error -"
+                      echo "$vcs_vers" | sed -e 's/^/ERROR /'
                       error_flag=1
                     else
-                      echo "INFO VCS is operational."
+                      echo "INFO VCS is operational"
                     fi
                     
                     # Check IMS
-                    if ! cray ims images list > /dev/null; then
-                      echo "ERROR IMS is not operational."
-                      error_flag=1
+                    ims_images_output=$(cray ims images list 2>&1)
+                    if [ $? -ne 0 ]; then
+                      echo "ERROR IMS is not operational"
+                      echo "ERROR <cray ims images list> failed with -"
+                      echo "$ims_images_output" | sed -e 's/^/ERROR /'
                     else
-                      echo "INFO IMS is operational."
+                      echo "INFO IMS is operational"
                     fi
 
                     # check the operating status of Nexus
                     res_file=$(mktemp)
                     http_code=$(curl -s -o "${res_file}" -w "%{http_code}" "https://packages.local/service/rest/v1/status")
-                    if [[ ${http_code} != 200 ]]; then
-                      echo "ERROR Nexus is not healthy."
+                    if [[ ${http_code} -ne 200 ]]; then
+                      echo "ERROR Nexus is not healthy. This check failed with return code $http_code since Nexus is unable to return its operating status"
                       error_flag=1
                     else
-                      echo "INFO Nexus is operational."
+                      echo "INFO Nexus is operational"
                     fi
 
                     # check for product catalog
-                    if ! kubectl get cm cray-product-catalog -n services > /dev/null; then
-                      echo "ERROR Cray Product Catalog configmap could not be found."
+                    result=$(kubectl get cm cray-product-catalog -n services 2>&1)
+                    if [ "$?" -ne 0 ]; then
+                      echo "ERROR Cray Product Catalog configmap could not be found"
+                      echo "$result" | sed -e 's/^/ERROR /'
                       error_flag=1
                     else
-                      echo "INFO Cray Product Catalog configmap exists."
+                      echo "INFO Cray Product Catalog configmap exists"
                     fi
 
                     exit $error_flag
diff --git a/workflows/iuf/operations/s3-upload/s3-upload-template.yaml b/workflows/iuf/operations/s3-upload/s3-upload-template.yaml
--- a/workflows/iuf/operations/s3-upload/s3-upload-template.yaml
+++ b/workflows/iuf/operations/s3-upload/s3-upload-template.yaml
@@ -72,16 +72,21 @@ spec:
                 PARENT_DIR=$(echo '{{inputs.parameters.global_params}}' | jq -r '.stage_params."process-media".current_product.parent_directory')
 
                 if [[ "${CONTENT,,}" == "null" ]] || [[ "$CONTENT" == "" ]]; then
-                    echo "ERROR current_product.manifest is null or empty"
+                    echo "ERROR Product manifest is null or empty"
                     exit 1
                 fi
 
                 if [[ "${PARENT_DIR,,}" == "null" ]] || [[ "$PARENT_DIR" == "" ]]; then
-                    echo "ERROR current_product.parent_directory is null or empty"
+                    echo "ERROR Extracted tarball directory is null or empty"
                     exit 1
                 fi
 
+                echo "INFO S3 uploading manifest for $PRODUCT from $PARENT_DIR"
                 /usr/local/bin/s3-upload "$CONTENT" "$PARENT_DIR"
+                if [ $? -ne 0 ]; then
+                  echo "ERROR S3 manifest upload failed for $PRODUCT from $PARENT_DIR"
+                  exit 1
+                fi
     - - name: s3-manufacture-product-catalog-data
         template: make-product-catalog-content
         arguments:
@@ -171,9 +176,10 @@ spec:
       image: artifactory.algol60.net/csm-docker/stable/docker.io/portainer/kubectl-shell:latest-v1.21.1-amd64
       command: [bash]
       source: |
+        PRODUCT=$(echo '{{inputs.parameters.global_params}}' | jq -r '.product_manifest.current_product.manifest.name')
         ARRAY=$(echo '{{inputs.parameters.manifest_s3_content}}' | jq -r '[.[] | {"bucket": .bucket, "key": .key}]')
         if [ $? -ne 0 ]; then
           ARRAY="[]"
-          echo "No S3 content found."
+          echo "INFO No S3 content found in the manifest for $PRODUCT"
         fi
         echo "{\"component_versions\": {\"s3\": ${ARRAY}}}" > /tmp/product-content
diff --git a/workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml b/workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
--- a/workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
+++ b/workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
@@ -185,9 +185,10 @@ spec:
             source_ns="$2"
             destination_name="$3-$RANDOM"
             destination_ns="$4"
-            if kubectl get $item_name -n $source_ns &> /dev/null; then
-              echo "Syncing $item_name from $source_ns to $destination_ns as $destination_name"
-              kubectl get $item_name -n $source_ns -o json | \
+            result=$(kubectl get $item_name -n $source_ns 2>&1)
+            if [ $? -eq 0 ]; then
+              echo "DEBUG  Syncing $item_name from $source_ns to $destination_ns as $destination_name"
+              result=$(kubectl get $item_name -n $source_ns -o json | \
                 jq 'del(.metadata.namespace)' | \
                 jq 'del(.metadata.creationTimestamp)' | \
                 jq 'del(.metadata.resourceVersion)' | \
@@ -196,10 +197,16 @@ spec:
                 jq 'del(.metadata.ownerReferences)' | \
                 jq 'del(.metadata.name)' | \
                 jq '.metadata |= . + {"name":"'$destination_name'"}' | \
-                kubectl apply -n $destination_ns -f -
-                return $?
+                kubectl apply -n $destination_ns -f -)
+                rc=$?
+                if [ $rc -ne 0 ]; then
+                  echo "ERROR  Creating secret $destination_name failed in $destination_ns namespace with error - "
+                  echo "$result" | sed -e 's/^/ERROR /'
+                fi
+                return $rc
             else
-              echo "Didn't find $item_name in the $source_ns namespace"
+              echo "ERROR  Didn't find $item_name in the $source_ns namespace"
+              echo "$result" | sed -e 's/^/ERROR /'
               return 1
             fi
           }
@@ -298,4 +305,10 @@ spec:
         image: artifactory.algol60.net/csm-docker/stable/docker.io/portainer/kubectl-shell:latest-v1.21.1-amd64
         command: [bash]
         source: |
-          kubectl -n argo delete secret/{{inputs.parameters.vcs_user_credentials_secret_name}}
+          vcs_secret_name={{inputs.parameters.vcs_user_credentials_secret_name}}
+          echo "DEBUG  Deleting secret $vcs_secret_name from argo workspace"
+          result=$(kubectl -n argo delete secret/$vcs_secret_name 2>&1)
+          if [ $? -ne 0 ]; then
+            echo "ERROR  Deleting secret $vcs_secret_name failed in argo namespace with error - "
+            echo "$result" | sed -e 's/^/ERROR /'
+          fi
