CASMINST-5842 run upload_ceph_images_to_nexus.sh as part of storage node upgrade

diff --git a/workflows/ncn/storage/storage.upgrade.yaml b/workflows/ncn/storage/storage.upgrade.yaml
--- a/workflows/ncn/storage/storage.upgrade.yaml
+++ b/workflows/ncn/storage/storage.upgrade.yaml
@@ -141,48 +141,12 @@ spec:
                   value: "{{$.DryRun}}"  
                 - name: scriptContent
                   value: |
-                    ts=$(echo $RANDOM | md5sum | head -c 20; echo)
-                    cat <<'EOF' > "/tmp/${ts}.sh"
-                    m001_ip=$(host ncn-m001 | awk '{ print $NF }')
-                    ssh-keygen -R ncn-m001 -f ~/.ssh/known_hosts > /dev/null 2>&1
-                    ssh-keygen -R ${m001_ip} -f ~/.ssh/known_hosts > /dev/null 2>&1
-                    ssh-keyscan -H "ncn-m001,${m001_ip}" >> ~/.ssh/known_hosts
-                    nexus_username=$(ssh ncn-m001 kubectl get secret -n nexus nexus-admin-credential -o json | jq '.data.username' | tr -d '"' | base64 --decode)
-                    nexus_password=$(ssh ncn-m001 kubectl get secret -n nexus nexus-admin-credential -o json | jq '.data.password' | tr -d '"' | base64 --decode)
-                    ssh_options="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
-                    function upload_image() {
-                        # get local image and nexus image location
-                        name=$1
-                        prefix=$2
-                        to_configure=$3
-                        local_image=$(ceph --name client.ro orch ps --format json | jq --arg DAEMON $name '.[] | select(.daemon_type == $DAEMON) | .container_image_name' | tr -d '"' | sort -u | tail -1)
-                        # if sha in image then remove and use version
-                        if [[ $local_image == *"@sha"* ]]; then
-                            without_sha=${local_image%"@sha"*}
-                            version=$(ceph --name client.ro orch ps --format json | jq --arg DAEMON $name '.[] | select(.daemon_type == $DAEMON) | .version' | tr -d '"' | sort -u)
-                            if [[ $version != "v"* ]]; then version="v""$version"; fi
-                            local_image="$without_sha"":""$version"
-                        fi
-                        nexus_location="${prefix}""$(echo "$local_image" | rev | cut -d "/" -f1 | rev)"
-
-                        # push images to nexus, point to nexus and run upgrade
-                        echo "Pushing image: $local_image to $nexus_location"
-                        podman pull $local_image
-                        podman tag $local_image $nexus_location
-                        podman push --creds $nexus_username:$nexus_password $nexus_location
-                    }
-                    prometheus_prefix="registry.local/artifactory.algol60.net/csm-docker/stable/quay.io/prometheus/"
-                    upload_image "prometheus" $prometheus_prefix "mgr/cephadm/container_image_prometheus"
-                    upload_image "node-exporter" $prometheus_prefix "mgr/cephadm/container_image_node_exporter"
-                    upload_image "alertmanager" $prometheus_prefix "mgr/cephadm/container_image_alertmanager"
-                    # mgr and grafana have this prfix
-                    ceph_prefix="registry.local/artifactory.algol60.net/csm-docker/stable/quay.io/ceph/"
-                    upload_image "grafana" $ceph_prefix "mgr/cephadm/container_image_grafana"
-                    upload_image "mgr" $ceph_prefix "container_image"
-                    EOF
-                    chmod +x /tmp/${ts}.sh
-                    scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/${ts}.sh {{$value}}:/tmp/${ts}.sh
-                    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{$value}} "/tmp/${ts}.sh"
+                    if [[ ! -f /usr/share/doc/csm/scripts/upload_ceph_images_to_nexus.sh ]]; then
+                      echo "ERROR  could not find file:/usr/share/doc/csm/scripts/upload_ceph_images_to_nexus.sh on ncn-m001. Please make sure you have the latest docs-csm installed."
+                      exit 1
+                    fi
+                    scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /usr/share/doc/csm/scripts/upload_ceph_images_to_nexus.sh {{$value}}:/srv/cray/scripts/common/upload_ceph_images_to_nexus.sh
+                    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{$value}} "/srv/cray/scripts/common/upload_ceph_images_to_nexus.sh"
           - name: upgrade-{{$value}}
             templateRef:
               name: ssh-template
