CASMINST-4942 fix storage.rebuild.yaml

diff --git a/workflows/ncn/storage/storage.rebuild.yaml b/workflows/ncn/storage/storage.rebuild.yaml
--- a/workflows/ncn/storage/storage.rebuild.yaml
+++ b/workflows/ncn/storage/storage.rebuild.yaml
@@ -1,6 +1,4 @@
 #
-# This file is for TESTING purposes only. Real workflows are found in docs-csm/workflows.
-#
 # MIT License
 #
 # (C) Copyright 2022 Hewlett Packard Enterprise Development LP
@@ -94,134 +92,146 @@ spec:
     - name: main
       dag:
         tasks:
-          {{- range $index,$value := .TargetNcns }}
+          {{- range $index,$value := .TargetNcns}}
           - name: upgrade-{{$value}}
             templateRef:
               name: ssh-template
               template: shell-script
             dependencies:
-              # each upgrade depends on previous upgrade action
+              # each upgrade depends on previous upgrade action and success
               # so we make sure only one node is drained at a time
               {{ if ne $index 0 }}
-              - upgrade-{{ index $.TargetNcns (add $index -1) }}
+              - check-ceph-health-{{ index $.TargetNcns (add $index -1) }}
               {{ end }}
             arguments:
               parameters:
-              - name: dryRun
-                value: "{{$.DryRun}}"
-              - name: scriptContent
-                value: |
-                /usr/share/doc/csm/upgrade/scripts/upgrade/ncn-upgrade-ceph-nodes.sh {{$value}}
+                - name: dryRun
+                  value: "{{$.DryRun}}"  
+                - name: scriptContent
+                  value: |
+                    echo "starting upgrade on {{$Value}}"
+                    upgrade_output=$(/usr/share/doc/csm/upgrade/scripts/upgrade/ncn-upgrade-ceph-nodes.sh {{$value}})
+                    echo ${upgrade_output}
           - name: check-ceph-health-{{$value}}
             templateRef:
               name: ssh-template
               template: shell-script
             dependencies:
               # check health once node upgrade is complete
-              - upgrade-{{$value}} 
+              - upgrade-{{$value}}
             arguments:
               parameters:
-              - name: dryRun
-                value: "{{$.DryRun}}"
-              - name: scriptContent
-                value: |
-                RESULT=$(/opt/cray/platform-utils/ceph-service-status.sh)
-                if [[ $RESULT -ne 0 ]]
-                  echo "ceph serice status check failed"
-                  exit 1
-                fi
-                RESULT=$(/opt/cray/platform-utils/ceph-service-status.sh -n {{$value}} -a true)
-                if [[ $RESULT -ne 0 ]]
-                  echo "ceph serice status check failed for node {{$value}}"
-                  exit 1
-                fi
+                - name: dryRun
+                  value: "{{$.DryRun}}"  
+                - name: scriptContent
+                  value: |
+                    RESULT=$(/opt/cray/platform-utils/ceph-service-status.sh)
+                    if [[ $RESULT -ne 0 ]]
+                      echo "ceph serice status check failed"
+                      exit 1
+                    fi
+                    RESULT=$(/opt/cray/platform-utils/ceph-service-status.sh -n {{$value}} -a true)
+                    if [[ $RESULT -ne 0 ]]
+                      echo "ceph serice status check failed for node {{$value}}"
+                      exit 1
+                    fi
           {{- end }}
           - name: rescan-ssh-keys
             templateRef:
               name: ssh-template
               template: shell-script
             dependencies:
-            # wait for health check of last storage node complete
-            - check-ceph-health-{{ with $length := len $.TargetNcns }}{{ index $.TargetNcns (add $length -1) }}{{end}}
+              # wait for health check of last storage node complete
+              - check-ceph-health-{{ with $length := len $.TargetNcns }}{{ index $.TargetNcns (add $length -1) }}{{end}}
             arguments:
               parameters:
                 - name: dryRun
                   value: "{{$.DryRun}}"  
                 - name: scriptContent
                   value: |
-                  grep -oP "(ncn-s\w+)" /etc/hosts | sort -u | xargs -t -i ssh {} 'truncate --size=0 ~/.ssh/known_hosts'
-                  grep -oP "(ncn-s\w+)" /etc/hosts | sort -u | xargs -t -i ssh {} 'grep -oP "(ncn-s\w+|ncn-m\w+|ncn-w\w+)" /etc/hosts | sort -u | xargs -t -i ssh-keyscan -H \{\} >> /root/.ssh/known_hosts'
+                    grep -oP "(ncn-s\w+)" /etc/hosts | sort -u | xargs -t -i ssh {} 'truncate --size=0 ~/.ssh/known_hosts'
+                    grep -oP "(ncn-s\w+)" /etc/hosts | sort -u | xargs -t -i ssh {} 'grep -oP "(ncn-s\w+|ncn-m\w+|ncn-w\w+)" /etc/hosts | sort -u | xargs -t -i ssh-keyscan -H \{\} >> /root/.ssh/known_hosts'
           - name: deploy-node-exporter-and-alertmanager
             templateRef:
               name: ssh-template
               template: shell-script
+            dependencies:
+              - rescan-ssh-keys
             arguments:
               parameters:
                 - name: dryRun
                   value: "{{$.DryRun}}"  
                 - name: scriptContent
                   value: |
-                  cat <<'EOF' > apply_exporter_alertmanager.sh
-                    ceph orch apply node-exporter && ceph orch apply alertmanager
-                    sleep 10
-                    # verify correct number of pods are running for node-exporter
-                    node_exporter_json=$(ceph orch ps --daemon_type node-exporter -f json-pretty)
-                    num_running=$(echo $node_exporter_json | jq '.[] | select(.status_desc=="running") | .hostname' | wc -w)
-                    if [[ $num_running -ne $(craysys metadata get num-storage-nodes) ]] || [[ $num_running -ne $(echo $node_exporter_json | jq '. | length') ]]
-                    then
-                      echo "Incorrect number of node exporter pods or not all pods are running"
-                      exit 2
-                    fi
-                    # verify refresh times for node-exporter
-                    refresh_times=$(echo $node_exporter_json  | jq '.[] | .last_refresh')
-                    for refresh_time in $refresh_times
-                    do
+                    cat <<'EOF' > apply_exporter_alertmanager.sh
+                      before_apply_time=$(date +%s)
+                      ceph orch apply node-exporter && ceph orch apply alertmanager
+                      sleep 10
+                      # verify correct number of pods are running for node-exporter
+                      node_exporter_json=$(ceph orch ps --daemon_type node-exporter -f json-pretty)
+                      num_running=$(echo $node_exporter_json | jq '.[] | select(.status_desc=="running") | .hostname' | wc -w)
+                      if [[ $num_running -ne $(craysys metadata get num-storage-nodes) ]] || [[ $num_running -ne $(echo $node_exporter_json | jq '. | length') ]]
+                      then
+                        echo "Error: Incorrect number of node exporter pods or not all pods are running"
+                        exit 2
+                      fi
+                      # verify refresh times for node-exporter
+                      refresh_times=$(echo $node_exporter_json  | jq '.[] | .last_refresh')
+                      for refresh_time in $refresh_times
+                      do
+                        refresh_time=$(echo $refresh_time | tr -d '"')
+                        refresh_time_SEC=$(date -d $refresh_time +%s)
+                        if [[ $refresh_time_SEC -lt $before_apply_time ]]
+                        then
+                          echo "Error: A node exporter was not refreshed after node exporter was deployed in the previous step."
+                          exit 3
+                        fi
+                      done
+                      # verify there is only 1 alertmanager
+                      alertmanager_json=$(ceph orch ps --daemon_type alertmanager -f json-pretty)
+                      if [[ $(echo $alertmanager_json | jq '. | length') -ne 1 ]]
+                      then
+                        echo "Error: Needs to be exactly 1 alertmanager"
+                        exit 4
+                      fi
+                      if [[ $(echo $alertmanager_json | jq '.[] | select(.status_desc=="running") | .hostname' | wc -w) -ne 1 ]]
+                      then
+                        echo "Error: Alertmanager is not running"
+                        exit 5
+                      fi
+                      refresh_time=$(echo $alertmanager_json  | jq '.[] | .last_refresh')
                       refresh_time=$(echo $refresh_time | tr -d '"')
                       refresh_time_SEC=$(date -d $refresh_time +%s)
-                      if [[ $refresh_time_SEC -lt before_apply_time ]]
+                      if [[ $refresh_time_SEC -lt $before_apply_time ]]
                       then
-                        echo "A Node exporter was not refreshed after node exporter was deployed in the previous step."
-                        exit 3
+                        echo "Error: Alertmanager was not refreshed after alertmanager was deployed in the previous step."
+                        exit 6
                       fi
-                    done
-                    # verify there is only 1 alertmanager
-                    alertmanager_json=$(ceph orch ps --daemon_type alertmanager -f json-pretty)
-                    if [[ $(echo $alertmanager_json | jq '. | length') -ne 1 ]]
-                    then
-                      echo "Error: Need to be exactly 1 alertmanager
-                      exit 4
-                    fi
-                    if [[ $(echo $alertmanager_json | jq '.[] | select(.status_desc=="running") | .hostname' | wc -w) -ne 1 ]]
-                    then
-                      exit 5
-                    fi
-                    refresh_time=$(echo $alertmanager_json  | jq '.[] | .last_refresh')
-                    refresh_time=$(echo $refresh_time | tr -d '"')
-                    refresh_time_SEC=$(date -d $refresh_time +%s)
-                    if [[ $refresh_time_SEC -lt before_apply_time ]]
-                    then
-                      exit 6
-                    fi
-                  EOF
+                    EOF
 
-                  # find storage node running ceph-mon
-                  storage_node=$(echo $(ceph -s -f json | jq '.quorum_names[0]') | tr -d '"')
-                  chmod +x apply_exporter_alertmanager.sh
-                  scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null apply_exporter_alertmanager.sh $storage_node:/tmp/apply_exporter_alertmanager.sh
-                  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $storage_node '/tmp/apply_exporter_alertmanager.sh'
+                    # find storage node running ceph-mon
+                    storage_node=$(echo $(ceph -s -f json | jq '.quorum_names[0]') | tr -d '"')
+                    chmod +x apply_exporter_alertmanager.sh
+                    scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null apply_exporter_alertmanager.sh ${storage_node}:/tmp/apply_exporter_alertmanager.sh
+                    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $storage_node '/tmp/apply_exporter_alertmanager.sh'
           - name: update-bss
             templateRef:
               name: ssh-template
               template: shell-script
+            dependencies:
+              - deploy-node-exporter-and-alertmanager
             arguments:
               parameters:
                 - name: dryRun
                   value: "{{$.DryRun}}"  
                 - name: scriptContent
                   value: |
-                  . /usr/share/doc/csm/upgrade/scripts/ceph/lib/update_bss_metadata.sh
-                  RESULT=$(update_bss_storage)
-                  # check that result contains success!
-                  
-       
-         
+                    . /usr/share/doc/csm/upgrade/scripts/ceph/lib/update_bss_metadata.sh
+                    RESULT=$(update_bss_storage)
+                    # check that result contains success!
+                    if [[ $RESULT != *"Success!"* ]]
+                    then
+                      echo "BSS metadata was not successfully updated. Output:"
+                      echo "$RESULT"
+                      exit 7
+                    fi
